### ISSUE TITLE
Newbie help

### ISSUE THREAD

**Issue by orecus** [rackt/redux#1021]
I've just started playing around with Redux and React and total new to this. I'm trying to get a basic login system working but I'm having a hard time with getting it to work with Redux. 

I've got the store, reducer and actions working properly when I'm testing them out by themself, but now that I'm trying to get them integrated into the actual thing I can't get it to build properly and it feels like I've been missing something fundamental here.

I have an index.js which includes routes with react-router (to be exchanged to redux-router, but one problem at a time), but from my understanding I need to move to use `class *** extends React.Component{}` instead for `React.createClass` which I now have started to move the loginForm over to as a first learning step. 

index.js
```javascript
import React from 'react';
import { render } from 'react-dom';

//Routing
import { Router, Route, IndexRoute } from 'react-router';
import createHistory from 'history/lib/createHashHistory';

//REDUX
import { Provider } from 'react-redux'
import configureStore from './configureStore'
const store = configureStore();

//Components
import Welcome from './components/welcome';
import loginForm from './components/login';
import Register from './components/register';

let history = createHistory({
    queryKey: false
});

function redirectToLogin(nextState, replaceState) {
    if (store.getState().auth.token === null || store.getState().auth.token === undefined) {
        replaceState({
            nextPathname: nextState.location.pathname
        }, '/')
    }
}

function redirectToApp(nextState, replaceState) {
    if (store.getState().auth.token) {
        replaceState({
            nextPathname: nextState.location.pathname
        }, '/welcome')
    }
}

render((
    <Provider store={store}>
        <Router history={history}>
            <Route path="/" component={App}>
                <IndexRoute component={loginForm} onEnter={redirectToApp} />
                <Route path="register" component={Register}/>
                <Route path="welcome" component={Welcome} onEnter={redirectToLogin}/>
            </Route>
        </Router>
    </Provider>
), document.getElementById('app'));
```

Babel Error:
```javascript
ERROR in ./src/client/components/login.jsx
Module build failed: Error: src/client/components/login.jsx: We don't know what to do with this node type. We were previously a Statement but we can't fit in here?
```

login.jsx
```javascript
import React, { Component, PropTypes } from 'react'

import View from 'react-flexbox';

//Redux
import { connect } from 'react-redux';

//Actions
import { doLogin } from '../actions/auth'

//Base Elements
var Typography = require('material-ui/lib/styles/typography');
var Spacing = require('material-ui/lib/styles/spacing');
var Paper = require('material-ui/lib/paper');

//UI-Elements
var RaisedButton = require('material-ui/lib/raised-button');
var TextField = require('material-ui/lib/text-field');

@connect(state => ({
    userEmail: '',
    userPassword: '',
    auth: state.auth
}))
export default class loginForm extends React.Component {
    static propTypes = {
        dispatch: PropTypes.func.isRequired
    };
    constructor() {
        super();
        this. _handleClick = this. _handleClick.bind(this);
    }
    _handleClick() {
        event.preventDefault();
        const { dispatch } = this.props;
        dispatch(doLogin(this.state.userEmail, this.state.userPassword));
    }
    render() {
        return (<Paper zDepth={1} rounded={false} style={{width: "600px", margin: "12em auto"}}>
            <header>
                <h3>You need to login to use this system.</h3>
            </header>
            <View row width="100%">
                <TextField
                    style={{margin: '1em'}}
                    valueLink={this.linkState('userEmail')}
                    id="userEmail"
                    fullWidth={true}
                    type="mail"
                    hintText="Enter your email address"
                    floatingLabelText="Email"
                    errorText="" />
                <TextField
                    style={{margin: '1em'}}
                    valueLink={this.linkState('userPassword')}
                    id="userPassword"
                    fullWidth={true}
                    type="password"
                    hintText="Enter your Password"
                    floatingLabelText="Password"
                    errorText="" />
            </View>
            <View auto row style={{margin: '1em auto'}}>
                <RaisedButton
                    onClick={this._handleClick}
                    fullWidth={false}
                    primary={true}
                    label="Login"
                    style={{margin: '0.5em'}} />
                <View auto row>
                    <RaisedButton
                        linkButton={true}
                        href="#/register"
                        fullWidth={false}
                        secondary={true}
                        label="Register"
                        style={{margin: '0.5em'}} />
                    <RaisedButton
                        linkButton={true}
                        href="#/lostpswd"
                        fullWidth={false}
                        primary={false}
                        label="Lost Password?"
                        style={{margin: '0.5em'}} />
                </View>
            </View>
        </Paper>);
    }
}
```

Any help and pointers would be greatly appreciated to get me going in the right direction.

**Comment by cappslock** [comment]
> from my understanding I need to move to use class *** extends React.Component{} instead for React.createClass which I now have started to move the loginForm over to as a first learning step.

I don't think this is necessarily true, everything should work fine with React.createClass if you prefer it or don't wish to migrate your code. If you do, I think people are now preferring pure functions for simpler components over ES6 classes when possible.

I see some syntax that is wrong or unfamiliar to me in your class, you may wish to configure Babel to get more specific errors on the lines which are failing since it seems like you're not getting quality errors out of it. A few things that caught my eye:

- ```    static propTypes = {
        dispatch: PropTypes.func.isRequired
    };``` This is not legal in a class definition, see React's docs on using ES6 classes.
- ```this. _handleClick = this. _handleClick.bind(this);``` Spaces?
- `<View row width="100%">` Here and other places, I am unfamiliar with providing a property to a React as a boolean without a value. Not saying it's not legal, I just don't think I've seen people do that before.

First and foremost, see if your transpiler strategy can emit better errors.

**Comment by gaearon** [comment]
Redux doesn't care whether you use createClass or ES6 classes.
There is nothing in this question specific to Redux.
Please keep using createClass if you have problems with ES6 classes.

If you use experimental features (decorators and static properties) make sure you're using Stage 0 preset for Babel. And we don't recommend using them—you won't find them in the official docs or examples.

The line inside the constructor indeed seems to have a problem with spacing. You should check the line number in Babel error message and fix it. This is the kind of question that is much better asked on StackOverflow because it is about ES6 syntax and not Redux.
