### ISSUE TITLE
.babelrc causing babel transpile issues 

### ISSUE THREAD

**Issue by tylerwgoza** [rackt/redux#1032]
Babel (according to it's website as of November 13, 2015) does not have an option for `stage` or `loose` and these cause babel to blow up on transpile. Wondering if this serves some other purpose?

**Comment by gaearon** [comment]
Please see the versions. The examples use Babel 5. Please consult Babel docs for migration instructions. We don't offer support for Babel in this repo. We'll switch to Babel 6 eventually, but for now, remember the examples are *Redux examples*, not project boilerplates. Consult them for the Redux-related parts of the code, but please don't consider them to always reflect the latest tools available.

**Comment by tylerwgoza** [comment]
Gotcha I will fork and not install your copy from npm. It fails from your module. This is not bolierplate, it is a library that causes my code to fail when building. I should not have to edit your accepted install just to build...

**Comment by gaearon** [comment]
>This is not bolierplate, it is a library that causes my code to fail when building.

The problem you have is due to you transpiling code from `node_modules`. You should **not** do that. That's a mistake in your build process.

If you process your code with `babel-loader` (Webpack) or `babelify` (Browserify), **you must exclude `node_modules` from your build process.** For example, in Webpack, in loader configuration you can write

```js
  {
    loader: 'babel-loader',
    exclude: /node_modules/
  }
```

or equivalent. You can also use `include` option to explicitly include the source of your application (this works better).

**Comment by tylerwgoza** [comment]
I see. I'll toss that in then. Thanks for the better explanation!

**Comment by gaearon** [comment]
You'll enjoy faster builds :wink:

**Comment by tylercollier** [comment]
Thanks Gaeron, that worked for me.
