### ISSUE TITLE
Interesting parallels between redux and http PATCH method?

### ISSUE THREAD

**Issue by brycehanscomb** [rackt/redux#1049]
I was reading up on how redux uses actions (usually [FSA](https://github.com/acdlite/flux-standard-action)s) to [describe changes that the state should undertake](http://rackt.org/redux/docs/introduction/ThreePrinciples.html), and it seems (cerebrally) similar to the intention of a properly implemented `PATCH` request.

In the [Three Principles section of the redux docs](http://rackt.org/redux/docs/introduction/ThreePrinciples.html), it's mentioned that:

> The only way to mutate the state is to emit an action, an object describing what happened...[actions are not data themselves] instead they  express an intent to mutate.

Which is strikingly similar to the way [William Durand and the RFC itself describes what the payload of a `PATCH` request is supposed to contain](http://williamdurand.fr/2014/02/14/please-do-not-patch-like-an-idiot/):

> The [payload] contains a set of instructions describing how a resource currently residing on the origin server should be modified to produce a new version.

Both seem to be a way to 'emit a mutation request' to a data store (whether a bona-fide redux store or the server's state). Was it intentional to create this parallel? Perhaps there could be some useful connection between the two and maybe even open up some interesting possibilities?

**Comment by gaearon** [comment]
Hi, thanks for posting an interesting observation. No, this is not intentional. Redux is primarily inspired by Flux and Elm, which themselves are influenced by CQRS and event sourcing.

I'm not really sure if there's any useful connection (other than that people can use it in articles as a metaphor). I'll close this as non-actionable but feel free to continue the discussion. :wink:
