### ISSUE TITLE
The case for e.g. immutable.js

### ISSUE THREAD

**Issue by marreman** [rackt/redux#1059]
I'm having trouble understanding pulling in something like immutable.js to turn your state tree immutable instead of just having some sort of middleware that clones the current state before dispatching the action. 

Can someone please enlighten me? =)

**Comment by simplesmiler** [comment]
@marreman better asymptotic memory use and simpler equality checks, I guess.

**Comment by gaearon** [comment]
You want to use ImmutableJS if you like its API and if your data is large and oft-changing. Re-creating large arrays and objects is costly, and Immutable solves this by structural sharing.

>instead of just having some sort of middleware that clones the current state before dispatching the action

That would be terribly inefficient (assuming you want to do this in production too). If you don't do this in production, then you have different behavior in dev and prod, which is also problematic because it's hard to debug production issues.
