### ISSUE TITLE
Safely deleting stores

### ISSUE THREAD

**Issue by Zacqary** [rackt/redux#1092]
We're in the process of migrating a pretty massive codebase to Redux, so we're doing it piecemeal by treating certain widgets that we're Reduxifying as "embedded Redux apps." So we're calling `Redux.createStore` multiple times, but only once per "app" — never for anything that's nested inside another Redux-using component. So it's technically not an anti-pattern? Okay, it's still an anti-pattern, but it's as anti-anti as possible given the situation.

Anyway, sometimes we need to destroy these embedded Redux mini-apps, so I need a way to do this that doesn't leak memory. Cleaning up the view is easy enough since it uses React: `ReactDOM.unmountComponentAtNode`. But what's the equivalent for Redux? Is `delete store` enough, or do I need to do something more intricate?

**Comment by gaearon** [comment]
@Zacqary Redux does not keep references to the store globally so there is no need to do anything like unmounting. Just make sure you're not holding a reference to the store object, and it will be garbage collected together with its state. That said it's unlikely this optimisation even matters unless we are talking about gigantic amounts of data.

**Comment by ahtesham-quraish** [comment]
@gaearon after logout from the app i want to clear the store because I have some checks on property which is stored in redux  store like code given below indicating with --> sign 

//App.js
import React from 'react';
// import { Link, IndexLink } from 'react-router';
import Head from './Header';
import {
    connect
} from 'react-redux';
import ReactDOM from 'react-dom';
import {
    browserHistory
} from 'react-router'

const App = React.createClass({

  handlerLogout: function(e){
    e.preventDefault();
    localStorage.token = "";
    browserHistory.push('/login');

    
  },
  render(){
      console.log("APP", this.props.state.loginReducer.get('isLoggedIn'));
    return (
      <div id="content-wrapper" ref='sidebar' className="">
     -->  { this.props.state.loginReducer.get('isLoggedIn') === true
       ? <Head onSubmitSidebarButton={this.handlerNavigtionButtonClick} onsubmitLogout={this.handlerLogout} ref="nav"/>
        : null

      }
        <section id="content-holder">
            {this.props.children}
        </section>
      </div>
    );
  }
});


    function mapStateToProps(state) {
        return {
            state: state
        }
    }

export default connect(mapStateToProps)(App);


routes are given below

export default (
  <Route path="/" component={App}>
    <IndexRoute component={requireAuthentication(Home)}/>
    <Route path="/home" component={requireAuthentication(Home)} />
    <Route path="/login" component={Login} />
    <Route path="ViewExamListing" component={requireAuthentication(ViewExamListing)} />
  </Route>
);
 what should i do to clear the store after or maybe before  moving to login page ???

**Comment by GanbilegBor-minted** [comment]
@gaearon 
even when there is no reference, I can still see that store exist because when an action that's common across all these stores, is executed I can see the same action log is being printed on console per store, including the one that is currently referenced and all the other previous ones that used to have references. Our app is pretty big that one app renders another app on a client side with ReactDOM.render when a button is clicked and whenever that happens we create a new store for that new app as we cannot use the existing because there'll be reducer name collisions. This sounds little hacky but I have my reasons like being able to lazy load the big JS for the second app etc. Because of this I'm worried about memory leak and the browser crashing, never actually ran to that issue but it's completely possible.

**Comment by markerikson** [comment]
@GanbilegBor-minted : The phrase "the store is being referenced by Redux" is not valid.  If you look at the source for `createStore`, it creates a closure, defines some functions, and returns an object with those functions.  That's it.  There's no additional tracking or "references" going on.

I'm also not sure I understand the problem you're describing.  What do you mean by "same action log is being printed on console per store"?  Can you give an example of what you're seeing?

**Comment by hostdp6** [comment]
I'm having a similar problem, and am looking for a way to solve it.  Here is the situation:

We have an "app platform" that hosts many react "apps".  Each "app" is basically a single screen with its own store.  For example, I have a list view that show the user all available objects and a detail view that allows the user to edit a single object.  The list view has a search functionality, and the search query is an attribute in the store for the list view.

When I navigate from the list view to the detail view, and then back to the list view my filter is basically saved.  To solve this, I would like to basically destroy my store in componentWillUnmount but I'm not quite sure how to do so.  So far, the best I have come up with is to dispatch an action that "resets" the store to its initial state but that feels like a hack.

**Comment by markerikson** [comment]
@hostdp6 : off the top of my head, just releasing any variables that point to the store and clearing out any subscriptions should be fine.  Also, dispatching a "RESET" action is a perfectly normal thing, and there's even some pre-made reducers that can help with that (see https://github.com/markerikson/redux-ecosystem-links/blob/master/reducers.md ).

**Comment by hostdp6** [comment]
Thanks @markerikson.  I ended up solving this as follows for future readers:

In my component, I modified the remove() function to dispatch a reset action:

'''
remove(){
      ReactDOM.unmountComponentAtNode(this.containerEl)
      store.dispatch(resetStore())
      super.remove()
    }
'''

Then, each reducer just returns its initial value when this action is dispatched.
