### ISSUE TITLE
Action Constants Style Question

### ISSUE THREAD

**Issue by thekevlau** [rackt/redux#1097]
It is my understanding that this VisibilityFilters js object (as seen copied from the example code on the Actions page of the Redux Docs) is never explicitly used to enforce that there can only be three values for visibilityFilter in the store? Since we can easily set visibilityFilter: "whatever we want" in the store via the action? and we do not have to set it to VisibilityFilters.property ?

Is there a point/are there any benefits or functional utility gained, beyond stylistic reasons and just to communicate that there are only three possible values of VisibilityFilters, to have a constant defined like this?:

```
// from the Actions page of the Redux Docs:
export const VisibilityFilters = {
  SHOW_ALL: 'SHOW_ALL',
  SHOW_COMPLETED: 'SHOW_COMPLETED',
  SHOW_ACTIVE: 'SHOW_ACTIVE'
}
```

Also, why is the naming style/convention of this particular constant different from all of the other constants defined above it? (that are all defined with entirely uppercase lettering)

**Comment by gaearon** [comment]
@thekevlau Don't read too much into this :-). It's just an example and there's no hidden sense here. We use constants mostly for documentation. Technically you could implement a check for valid values but we didn't bother to do this because it distracts from the example. Finally, I'm not sure what style change you are referring to, but in any case, it has nothing to do with Redux. Please use any style you consider appropriate. There's nothing particularly "right" about the style we use in docs. We always discuss important parts (such as reducer purity). The rest is up to you.

**Comment by thekevlau** [comment]
@gaearon cool! thanks for the quick response :)
