### ISSUE TITLE
real-world example's redux-devtools is not work.

### ISSUE THREAD

**Issue by jcs12311** [rackt/redux#1110]
platform: ubuntu 14.04
node: v4.0.0
![1111](https://cloud.githubusercontent.com/assets/7412060/11623612/0feeb578-9d09-11e5-89bb-8ea3352914c2.png)

**Comment by jcs12311** [comment]
The error was occur when i click the dev tool panel

**Comment by ellbee** [comment]
Thanks for the report, I am looking into it.

**Comment by ellbee** [comment]
Oh, I think this is a problem I've run into a number of times where `redux-router` and `redux-devtools` don't play nicely together. When you click `RESET` the router state is reverted to null and that line that is throwing the error is trying to read `state.router.params`. Let me know if you caused this to happen in any other way than clicking `RESET` or `REVERT` and I'll look into it further.

**Comment by jcs12311** [comment]
Yes, not only  RESET or REVERT. the button like @@INIT, USER_REQUEST and so on are not work.

**Comment by gaearon** [comment]
Whenever you remove the very first action (whether reset/revert, or by clicking that action) Redux Router breaks. This is really an issue with Redux Router I think. We'll probably be switching to Redux Simple Router anyway because that's what community favors.

**Comment by jcs12311** [comment]
thanks @gaearon  @ellbee

**Comment by jackyon** [comment]
same issue happened to me.
@gaearon so... it is mean we can't use Redux Router and Redux-devtools at same time?

plz advise.
thx.

**Comment by gaearon** [comment]
You can't toggle the first action. Everything else works.

**Comment by jackyon** [comment]
yes, I can toggle the other action now, but the top right buttons still not working. (reset, revert...)

**Comment by ellbee** [comment]
You can sort of get it to work with some exceptions:

* Click Commit immediately when you start your session. Revert will then work.
* Reset will never work. Don't click it. 
* The first `redux-router` action will break too, don't click that also. 
* Everything else should work.
* If you click Revert (without Commit first), Reset or the first action nothing will work until you refresh. 

As mentioned the problem is really in redux-router. You might consider switching `redux-router` out for `redux-simple-router`, it does not have this problem.

**Comment by ellbee** [comment]
With regards to `redux-simple-router`, I should mention that full devtools support will be in the v1.0.0 release which will be released in the next few days. The current 0.10 release has a problem where you can't disable actions.

**Comment by jackyon** [comment]
thanks for reminding that!
