### ISSUE TITLE
Nested store provider, is it bad ?

### ISSUE THREAD

**Issue by CodeRiderz** [rackt/redux#1113]
Hi guys, Is it good to have nested store provider ? 
Or it's better keep all reducers in one root store provider ?
I use root store provider to keep the auth informations (tokens, activeUsers, etc ), and global visibility filters for UI such as modalbox, sidebar nav, etc.
Since my application getting bigger, and I want to separate the store providers, but there will be a root provider to connect those child store providers. But I'm having a trouble to connect parent and child provider.
Do you use the same approach ? If yes, then how to connect stores between parent child store providers? 
If not, what is the best approach for big applications with many reducers ?

Thank's.

**Comment by gaearon** [comment]
I think you're confusing a store and a `<Provider>` component. Store holds your data. `<Provider>` is just a React component that makes your store implicitly accessible to `connect()`ed components below. There is no such thing as a “store provider”—we never use this term in the docs.

In 99% Redux apps you will see only one store. That's most likely all you need.

>If not, what is the best approach for big applications with many reducers ?

Use `combineReducers()` to separate them. You can use it multiple times if you like. Check out `shopping-cart` example in this repo for an example of that. Otherwise I'm not sure what exactly you want to separate.

Finally, this question is better suited for StackOverflow.

**Comment by CodeRiderz** [comment]
Please forgive me, for asking here.
Thank's, for the answer.

**Comment by gaearon** [comment]
No problem! Don't worry—it's just that SO questions and answers are *way* easier to search (and later they are ranked so common questions get to the top instead of being buried in Github Issues).

**Comment by sompylasar** [comment]
@gaearon Just a note. StackOverflow tends to contain a multitude of low quality answers, the quality there is much less than here, on GitHub. Probably, because it's a self-driving non-moderated community of individuals trying to "help" each other with "I don't know for sure, but try this, maybe it will work" answers, in contrast to GitHub which is moderated by the repo maintainers who hold the initial knowledge on the topic.

**Comment by gaearon** [comment]
@sompylasar I believe it's job of the author to promote their question and post a link to those interested in giving great answer. Surely you get a lot of nonsense replies, but for greatly phrased questions this is rarely the case. For example most of these have good answers: http://stackoverflow.com/questions/tagged/redux?sort=votes&pageSize=50

**Comment by sompylasar** [comment]
@gaearon :+1: right, I see you answer them, too, that's great.
