### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by pietropizzi** [rackt/redux#1127]
Could you create a new release on npm? Version 3.0.4 is already over 170 commits back and there are some interesting fixes.

**Comment by markerikson** [comment]
Not sure what fixes you're referring to.  The commit activity has been almost entirely doc-related.  3.0.4 was released on Oct 23, and looking at the [commit history for /src](https://github.com/rackt/redux/commits/master/src), there's been no meaningful changes.  Only two commits have modified the actual source since then, and both were just stylistic cleanup.

**Comment by pietropizzi** [comment]
for me it would be mostly about this: https://github.com/rackt/redux/pull/1039 it get's rid of the `.babelrc` file on npm and the makes it compatible with Rect Native 0.16

**Comment by gaearon** [comment]
I released 3.0.5 as a hotfix for this.
Please let me know if it helps.

**Comment by pietropizzi** [comment]
Thanks @gaearon, much appreciated!
