### ISSUE TITLE
Add routing to universal example

### ISSUE THREAD

**Issue by ads1018** [rackt/redux#1143]
What do you guys think about adding routing to the universal example? I'm looking for a good redux universal redux starter kit and this would be perfect but I'm not sure the best way to implement routing.

**Comment by gaearon** [comment]
I agree Universal example needs routing. We want to migrate Real World example to [redux-simple-router](https://github.com/jlongster/redux-simple-router), and we should probably use it in Universal example too.

**Comment by acjay** [comment]
:+1: I just got universal routing working with [redux-simple-router](https://github.com/jlongster/redux-simple-router), and it seems like a very clean solution. The only thing that feels like a missing piece now is there isn't any mechanism, like Relay, to make fetching the data needed for the selected route declarative.

**Comment by sompylasar** [comment]
@acjay maybe "fetching data for the components rendered on the selected route"?

**Comment by acjay** [comment]
Yeah, same meaning. I probably shouldn't have tried to wrap up so many things into one sentence. Basically, I'm interested in a system that allows components to declare the data they need, bubbles that up to the routing layer, and then fetches that data. Like Relay. :)

**Comment by sompylasar** [comment]
@acjay I think the components should handle the "no data yet" (or "data is loading") state, too. The declarative requirements should not pause rendering, they should just start async requests that, upon start, will set some "loading" flag on the store, and, upon completion, will dispatch the results, populate the store with them and clear the "loading" flag.

**Comment by CrocoDillon** [comment]
I was thinking of creating middleware that does just that, keep track of any pending async actions (promises) so you can do something when they are resolved.

The thing that bugs me is exactly what @acjay mentions, you don't know what data you need before the components are rendered. So that means you have to render twice, which is too costly unless you can cache the results. Flow would be render > wait for async actions to get the data > get a snapshot of the current state > re-render with that state.

**Comment by sompylasar** [comment]
It's the purpose of React to optimize the cost of re-renders.

The "not loaded", "loading", "loaded successfully" and "load error" are
distinct states that should be handled by the app UI components. A
component can stay in one of these states for a long time. No need to
organize a separate store for the states of these pending requests inside
some middleware, Redux already provides a mechanism to manipulate state.

**Comment by CrocoDillon** [comment]
I'm talking about server-side rendering, for example an article on a blog.

**Comment by acjay** [comment]
@sompylasar That's definitely a possible approach. I think that's especially great for the client side, where a loading state might have a visual manifestation that has utility. But it's weird to me to put a whole bunch of loading behavior in the `render` call tree, as well as doing the bookkeeping of tracking when final render has occurred through Redux.

Then again, perhaps it's not crazy, because at least you're truly letting data dependencies derive directly from rendering needs. So then you'd have:

- server-side rendering app root level
  - match route 
  - render components with an empty store, instrumented with request capture middleware

    (This would essentially fan-out a request for data requests)

    - capture data request actions in middleware
  - issue aggregated data fetch from captured data requests

    (Use the end of synchronous render as a signal that we've fully aggregated all requirements)

  - discard original store and rendered result
  - create new store with updated data (no need for middleware here)
  - render components
  - deliver page

I don't know a whole lot about the details of Relay in practice, but I would suppose something similar to its query fragments could be used to describe data dependencies, and something similar to its GraphQL fetching engine could be used to aggregate them. Perhaps Relay itself could be used.

**Comment by DenisIzmaylov** [comment]
A few months ago I have described those steps in the example for my middleware `redux-catch-promise`: 
https://github.com/DenisIzmaylov/redux-catch-promise

**Comment by acjay** [comment]
@DenisIzmaylov That's hilarious! That's about as close to what I had in mind as I could imagine.

**Comment by pavelkornev** [comment]
@acjay take a look at https://github.com/erikras/react-redux-universal-hot-example, especially on [transitionMiddleware](https://github.com/erikras/react-redux-universal-hot-example/blob/master/src/redux/middleware/transitionMiddleware.js) and [getDataDependencies](https://github.com/erikras/react-redux-universal-hot-example/blob/master/src/helpers/getDataDependencies.js)

**Comment by pavelkornev** [comment]
@gaearon what is the best approach to fetch async data for a component's tree for a server side rendering in Redux app?

**Comment by gaearon** [comment]
Dispatch async actions and wait for them to finish?

**Comment by CrocoDillon** [comment]
@pavelkornev I use and adapted version of redux-thunk that saves promises returned from thunks, that way you can do something when all promises are resolved. Not totally happy about the API I've come up with but it gets the job done nicely.

You need to trigger fetches before rendering (because otherwise you need to render twice), I found React Router's `onEnter` function useful for that. Then you just need to wait till all promises are resolved to render your app. Using `onEnter`'s callback argument might be tempting, but that makes fetches sequential instead of parallel when child routes need to fetch too... so it's better to not use that.

Example implementation available [here](https://github.com/CrocoDillon/universal-react-redux-boilerplate/blob/master/src/server.jsx#L30-L41). I'm hoping to get some feedback there so if you have any please don't hesitate!

**Comment by acjay** [comment]
@pavelkornev That is *slick*! I'm going to have to dig into that. I've only glanced through it so far, but is it correct to say that it delegates responsibility for fetching to the components named in the React Router routes, via `fetchData` and `fetchDataDeferred` methods they can optionally provide? If so, I suppose they'd have to be responsible for (and coupled to) their respective dependency subtrees, but any amount of delegation seems like the right direction.

**Comment by pavelkornev** [comment]
@CrocoDillon hm, isn't it the same approach as ```fetchData``` mentioned in React docs and implemented in react-redux-universal-hot-example (see links below)?

@gaearon absolutely, but community of noobs need a simple example of it with complete explanations, it's really high learning curve. BTW, thanks for your egghead's free of charge lessons, that brought some light in my dark tunnel!

@acjay i'm also on the way to understand how things work. As i understood that implementation in [react-redux-universal-hot-example](https://github.com/erikras/react-redux-universal-hot-example) is exactly correspond to [this statement in Redux docs](https://github.com/rackt/redux/blame/master/docs/recipes/ServerRendering.md#L285). No matter was component named in routes directly or it someone's child component, if it has ```fetchData``` method this method will be called during server request if that component is in component's tree which has to be rendered on this request. So, the only convention here is method's name.

**Comment by CrocoDillon** [comment]
I'm also a beginner and probably wrong on too many things, still I want to mention how my approach is different (and still more or less the same like you said).

- Different static method name, I kept it more generic and called it `onEnter` to match `Route`'s `onEnter` prop. The reason is I want to do more than just fetching data, for example logging requests or storing data after a POST request. Basically everything has to work when JS is disabled (client-side rendering as enhancement). Anyway... what's in a name? :)
- Explicit `onEnter` props in the routes, that way it's easy to see in a glimpse what routes/components rely on this. Less magic, I think that's a good thing and makes the code easier to understand for beginners.
- Totally different way of knowing when promises resolved because [mutating Redux state](https://github.com/erikras/react-redux-universal-hot-example/blob/ef6eb4d7ff374b4955b4903a740743e0fa00f412/src/redux/middleware/transitionMiddleware.js#L37) is a bit unwieldy (and feels wrong). Not saying I'm 100% happy about my method.

**Comment by buzinas** [comment]
@gaearon Are you guys sill planning to do this?

**Comment by gaearon** [comment]
There is a bunch of open PRs, one of them does that. I’ll try to merge them as soon as I get some time.
