### ISSUE TITLE
To create store with initial state, object can only contain keys that match the function names of the reducers

### ISSUE THREAD

**Issue by davidhtien** [rackt/redux#1158]
`createStore(attendance, {handleWeek: initialState})` works but
`createStore(attendance, initialState)` doesn't where initialState is a normal javascript object and my reducers is simply

```
function handleWeek(state = date, action) {
   ...
}

const attendance = combineReducers({
  handleWeek
})

export default attendance
```

**Comment by gaearon** [comment]
This is expected. If you want to pass initial state of just a single reducer, use *that* reducer when creating a store. That is, call `createStore(handleWeek, initialState)` and remove `combineReducers()` call because apparently you don't want to have several keys.

Please look at `combineReducers()` documentation for more detail. It is not something you *have* to call in every app. Rather, it is a convenient helper to generate a reducer that delegates parts of the state to several other reducers. It doesn't really make sense to call `combineReducers()` with a single key because you can just use *that* reducer instead.

**Comment by davidhtien** [comment]
thank you for that super quick and helpful answer! that makes it very clear, I had a wrong understanding of combineReducers()
