### ISSUE TITLE
Codesplit + HMR without getReducer

### ISSUE THREAD

**Issue by mattkrick** [rackt/redux#1163]
I can see how to HMR via the examples in this repo (thanks!).
I can see how to codesplit via http://stackoverflow.com/questions/32968016/how-to-dynamically-load-reducers-for-code-splitting-in-a-redux-application

What isn't obvious is how to combine them without access to the internal `currentReducer` since an HMR is going to wipe out my `asyncReducers` object when it reloads. Looking through the old issues, I saw that `getReducer` was removed, so now I'm wondering if this is still possible (without doing something ugly like saving a copy of the reducer to `window.currentReducer`.

**Comment by gaearon** [comment]
Please ask questions on StackOverflow rather than in issues.

That said you probably want to look at the [HMR API](https://webpack.github.io/docs/hot-module-replacement.html) in more detail. It lets you save data in a `dispose()` handler which will later be available as `module.hot.data` on the re-evaluated module.
