### ISSUE TITLE
Reducer without switch

### ISSUE THREAD

**Issue by mapreal19** [rackt/redux#1167]
As reading from the [docs](http://redux.js.org/docs/recipes/ReducingBoilerplate.html) you could avoid using `switch` with a function that maps action types to handlers. But still I'm not fully convinced with that approach. 

In order to avoid those long switch statements, I suggest injecting the dependency of the reducers right into the actions. 

The actions now will know how to change the state per each reducer. The reducer will just call them accordingly. This way, the reducer would follow the Open/Closed principle (Motivation by Uncle Bob: https://youtu.be/TMuno5RZNeE?t=3605)

I found this architecture much better. Take the case your system requires a new feature where 3 reducers listen to the same action. Then you would need to modify those reducers -- adding a new case on each switch statement.

Following the style I propose, you would only need to create the action with the reducers all in the same place. Example:
   
    // ACTION
    function addTodo() {
      reducers: {
        counterReducer: (state) => ...,
        todosReducer: (state) => ...,
        dummyReducer: (state) => ...
      }
    }

    // todos REDUCER
    function todos(state = initialState, action) {
      if (action.reducers && typeof action.reducers.todosReducer === 'function') {
        return action.reducers.todosReducer(state);
      } else {
        return state;      
      }
    }

[Here](https://github.com/mapreal19/redux/pull/1/files) you could see a refactor of the todomvc example using this idea.

Thoughts?

**Comment by theaqua** [comment]
[redux-actions](https://github.com/acdlite/redux-actions) and [`handleActions`](https://github.com/acdlite/redux-actions#handleactionsreducermap-defaultstate).

**Comment by gaearon** [comment]
The whole point of Flux/Redux is to decouple actions and reducers. There may be many independent reducers handling one action, and there may be many independent actions handled by one reducer. This is what makes Flux/Redux scale because big teams can work on overlapping features without constant merge conflicts, as state mutation logic is kept separate even if it is caused by the same actions.

You also lose the ability to serialize and record/replay actions because they are not plain objects any more in your example. Enabling this was another big constraint of Redux. Please [read this](http://redux.js.org/docs/recipes/ReducingBoilerplate.html):

>There are frameworks claiming to be similar to Flux, but without a concept of action objects. In terms of being predictable, this is a step backwards from Flux or Redux. If there are no serializable plain object actions, it is impossible to record and replay user sessions, or to implement hot reloading with time travel. If you’d rather modify data directly, you don’t need Redux.

**Comment by gaearon** [comment]
Think of action as a "message". The action doesn't *know* how the state changes. It's precisely reducers' job. Otherwise your reducers don't seem to contain code at all. Also don't forget that reducers can be composed further than a single level. What you propose doesn't work with reducer composition because you're effectively hardcoding reducer structure into the action objects.

**Comment by mapreal19** [comment]
I see. Thank you for the quick feedback @gaearon :+1:

**Comment by negamaxi** [comment]
Well, personally I hate switch so I use plain objects instead:
```javascript
const actionHandlers = {
  [ADD_TODO] (state, todo) {
    // do stuff
  },
  [REMOVE_TODO] (state, id) {
    // do stuff
  }
}

const reducer =  (state = initialState, action) => {
    const { type, payload } = action
    const actionHandler = actionHandlers[type]
    if (actionHandler) {
      return actionHandler(state, payload)
    }
    return state
  }

**Comment by batcer** [comment]
@negamaxi What does this syntax mean that you use? 
```
[ADD_TODO] (state, todo) {
    // do stuff
  },
```
