### ISSUE TITLE
Looking for Feedback: Some new ideas to build a Redux app

### ISSUE THREAD

**Issue by arunoda** [rackt/redux#1168]
I'm experimenting with some new ideas to build a Redux app. Here are some those changes:

* Using a new router, which simply dispatch actions.
* Using a layout to render components based on routes.
* Using a ducks like directory architecture.
* Using a simple helper to load data before component is rendered.

Here's the sample app: https://github.com/kadira-samples/rethinking-redux-demo

Here's my writing about it and a video walkthrough into the codebase: [Rethinking Redux](https://voice.kadira.io/rethinking-redux-f1e96daba60c#.eh2cag0t0)

Looking forward for some feedback.

**Comment by grigio** [comment]
Good points!

> - Using a new router, which simply dispatch actions.

This is very important for me and this is why I looked at [CerebralJS](http://www.cerebraljs.com/routing) instead of Redux (+ react-router).

**Comment by urbanvikingr** [comment]
@arunoda I use a Router reducer and a Layout component for my single page application. I currently use the Redux directory structure, because I started with it.

I also reuse my Reducer state in my components e.g. currentUser state is used by Navigator component as well as Account -> EditUser component (profile).

I like the idea of helper / utils to load data before rendering. It could help me to convert some of the "class" components to functional stateless components.

**Comment by arunoda** [comment]
@urbanvikingr Thanks.

I think, data loader utility is pretty useful. I'll try to isolate and create a npm module. 

A lot of guys have suggested me to use the [redux-simple-router](https://github.com/rackt/redux-simple-router). I'm going to give it a try.

**Comment by arunoda** [comment]
I tried `redux-simple-router` and it worked. Unfortunately, I can't do hot reloading. Anyway, that fine.
But with my original approach, hot reloading works nicely.

**Comment by arunoda** [comment]
I'm gonna close this. But, I'm in need of more suggestions :)

**Comment by urbanvikingr** [comment]
@arunoda A finale note, your diagram states that Reducers replace State; they create a new State (current State plus changes). This is a very important point. State is immutable. You also haven't divided React components into Containers (know about Reduct) and regular Component (doesn't about Redux).

**Comment by arunoda** [comment]
Yeah! It's not replacing the state. Do you any way to put it in a diagram.

Actually, about the React components. In my app, all of the components are functional React components. They know nothing about Redux.
See: https://github.com/kadira-samples/rethinking-redux-demo/blob/master/src/modules/single_post/view.js#L9

I could simply export them and write some test cases. I find it simple to put both of them in a single file for the readability. Separating it to a new file is also a good idea. But I don't see anything wrong with putting them in a single file. (Since, we are not creating any Redux related components manually. I simply use `loadData` and `connect`). 

Do you see any issue with that?

**Comment by arunoda** [comment]
Hey @urbanvikingr could you have a look at the project now. I re-arrange files a bit based on your feedback.
See: https://github.com/kadira-samples/rethinking-redux-demo

I also changed the diagram a bit too. See: https://voice.kadira.io/rethinking-redux-f1e96daba60c#.afxyk4s09

**Comment by mordra** [comment]
I find this point of the post to be very misleading:
We use a pure function, which listens to all the actions and mutates the state. We called this the reducer. It’s the only place where we can mutate the state.

It really should read:
We use a pure function, which listens to all the actions and **uses the current state as a context to produce the next state**. We called this the reducer.
The reducer is a pure function because it does not mutate the state and it does not have any side effects.

And the diagram is also misleading because it reinforces the idea that the reducer takes the state and writes back to the state as a single object. However the state is really a chain of objects linked by actions.

**Comment by arunoda** [comment]
@mordra I think this description is pretty great. I update it. 

One question.
State is updated by reducer as a single object. (Assume in the case of the root reducer). So, basically original state is updated as a whole.
BTW: I got your point as well. But I think it's hard to re-present the whole idea behind Redux in a diagram. I'm clueless to modify it further.

**Comment by urbanvikingr** [comment]
@arunoda I think the official Redux documentation explains it very well. I recommend to refer to this instead and give credit to Dan. This way, you don't need to write something that is already written. It was also my understanding that you wanted to rethink Redux. I would like to hear about this in your blog - what you would like to change, how you plan to do so and why. It would be interesting to see your results.

**Comment by arunoda** [comment]
@urbanvikingr That's sound great. I already mentioned his EggHead video series. I'll update it. 
And will do a follow-up blog post with the result. I could be able to shape my sample app and now we are readying to build a kind a large app in Redux.
