### ISSUE TITLE
How should (un)subscribing in the middle of dispatch work?

### ISSUE THREAD

**Issue by gaearon** [rackt/redux#1180]
Here's something that came up a few times: https://github.com/gaearon/react-dnd/issues/307#issuecomment-148528999

We let people subscribe and unsubscribe during a dispatch. This is not a problem per se.

The current behavior is that subscribe during dispatch only takes effect the next time. So if you subscribe from during a dispatch, you will only be called on next dispatch. **This doesn't seem problematic** because you can just read the initial state and rely on the subscriber being called the next time. It doesn't violate your expectations.

The current behavior is also that *unsubscribing* during dispatch only takes effect *after* the dispatch. So if I unsubscribe, but I'm in the middle of dispatch *and* the subscriber hasn't been called yet, it *will* be called. Even though I unsubscribed. **This seems problematic** because unsubscribing carries an expectation that I won't ever be called again unless I subscribe. However we violate this expectation.

One thing we can do is to treat unsubscriptions *while dispatching* in a special way and put those listeners in a special array. When dispatching we can make sure to skip those listeners. However this seems like a perf problem for a rare case.

We might also choose to not fix this, and document this behavior. Then it'll be up to consumers like React Redux to protect themselves from it. (FWIW React Redux already handles this correctly.)

**Comment by slorber** [comment]
Incriminated line: `listeners.slice().forEach(listener => listener())` 

So on every dispatch you copy the whole listener array :) I understand the benefit of this to avoid weird index issues when modifying the array while iterating it. However it's still already a copy on each dispatch and has a performance cost (that probably does not matter much).

IMO the solution does not need to have any perf problem and could even give better performances.

Instead of using a forEach maybe it would be possible to modify the listeners array in place without having any issue during the iteration process? 

I don't know what's the best solution but a solution could be to replace the listener by undefined in the array on unsubscribe, and skip undefined listeners while iterating. At some point the array should be cleaned from undefined listeners (when?) and it may affect performances but you removed the array copy on every dispatch so it might be ok.


How react redux handles this btw?

**Comment by Aweary** [comment]
What if instead of just calling `slice` in the `ubsubscribe` function, it checked whether `isDispatching` was true, and just registered the index of the listener in a new array instead.

```js
...
function unsubscribe() {
      if (!isSubscribed) {
        return
      }

      var index = listeners.indexOf(listener)

     if (isDispatching) {
        indexList.push(index)
        return
     }

      isSubscribed = false
      listeners.splice(index, 1)
    }

```

Then you could filter out listeners after your `slice` at that index

```js
listeners.slice().forEach((listener, index) => {
     if (indexList.includes(index)) return;
     listener()
})
```

As long as the `unsubscribe` call was made before the `listeners` array reached the corresponding index, that should skip it. Then after the listeners have been invoked the `listeners` array could be cleaned up.

**Comment by slorber** [comment]
Hi,

I've made a pull request to try to solve this.

It passes npm run check and has a new test case added:

```javascript
  it('removes listeners immediately when unsubscribe is called', () => {
    const store = createStore(reducers.todos)

    const unsubscribeHandles = []
    const doUnsubscribeAll = () => unsubscribeHandles.forEach(unsubscribe => unsubscribe() )

    const listener1 = expect.createSpy(() => {})
    unsubscribeHandles.push(store.subscribe(listener1))
    const listener2 = expect.createSpy(() => {})
    unsubscribeHandles.push(store.subscribe(listener2))

    const listener3 = () => doUnsubscribeAll()
    unsubscribeHandles.push(store.subscribe(listener3))

    const listener4 = expect.createSpy(() => {})
    unsubscribeHandles.push(store.subscribe(listener4))
    const listener5 = expect.createSpy(() => {})
    unsubscribeHandles.push(store.subscribe(listener5))

    store.dispatch(unknownAction())
    expect(listener1.calls.length).toBe(1)
    expect(listener2.calls.length).toBe(1)
    // listener3 is the one removing the others so obviously it got executed
    expect(listener4.calls.length).toBe(0)
    expect(listener5.calls.length).toBe(0)
  })
```

I don't think it impacts too much performances

**Comment by slorber** [comment]
@gaearon it makes me think: if a listener fails, shouldn't the next listeners still be triggered?

**Comment by le0nik** [comment]
Could this be a bit more simple and readable, instead of keeping a separate array for invalid listeners and cleaning it up afterwards? 

```
    listeners.slice().forEach(listener => {
      // Check if subscription is still intact
      if (listeners.includes(listener)) {
        listener();
      }
    });
```

There is some performance penalty one way or another, but if everyone agrees, that this is the correct logic, then i don't think it matters that much. Just my 2 cents.

**Comment by slorber** [comment]
@gaearon I think i'll rework my PR with @le0nik solution which is more clean.

Also I think if we register a listener during a dispatch, that listener should rather not be called and my PR does not handle this case currently (I think) while the former code did not have this behavior.


@gaearon don't know if I should use array.include as it seems an ES7 method right?

**Comment by slorber** [comment]
@gaearon I added that test case as well (it was already passing btw):

```javascript
  it('not fire immediately if a listener is added inside another listener', () => {
    const store = createStore(reducers.todos)

    const listener1 = expect.createSpy(() => {})
    const listener2 = expect.createSpy(() => {})
    const listener3 = expect.createSpy(() => {})

    let listener3Added = false;
    const maybeAddThirdListener = () => {
      if ( !listener3Added ) {
        listener3Added = true;
        store.subscribe(() => listener3())
      }
    }

    // Listener 1 is normal
    store.subscribe(() => listener1())

    // Listener 2 adds the 3rd listener another listener
    store.subscribe(() => {
      listener2()
      maybeAddThirdListener()
    })

    store.dispatch(unknownAction())
    store.dispatch(unknownAction())
    expect(listener1.calls.length).toBe(2)
    expect(listener2.calls.length).toBe(2)
    expect(listener3.calls.length).toBe(1)
  })
```

Also used @le0nik's solution as it seems a lot more easy than my original attempt :)

**Comment by slorber** [comment]
@tappleby do you still have problems with batched-subscribes with the solution of @le0nik  implemented in my PR ? https://github.com/rackt/redux/pull/1204

**Comment by tappleby** [comment]
@slorber The implementation looks good, although I do like the idea of just setting the value to `undefined` instead of removing it immediately from the array (see [my comment](https://github.com/rackt/redux/pull/1204#issuecomment-169526695) on PR #1204), prevents having to duplicate the array on every dispatch. 

My issues were more with having to duplicate the logic (which is fine if its simple).

**Comment by slorber** [comment]
@tappleby yes copying the array is a drawback but the solution is much simpler like that and it did copy the array before so... and you can easily copy that logic :) maybe it's too soon for doing this kind of optimizations I like the redux core to be easy to read even if it copies the array on every dispatch. Let @gaearon decides that

**Comment by gaearon** [comment]
I'm inclined to leave things as is. The benefit (slightly "smarter" model) doesn't seem worth the complexity, and you can implement it in userland too with a custom event emitter acting as a sole subscriber. Instead, we documented the current behavior: https://github.com/rackt/redux/commit/6de0cda36ec6fe2c7aab52f055f59040488763e3.

**Comment by slorber** [comment]
@gaearon I agree.

I've made another PR with the 2 tests I have done, slightly modified so that they cover your decision:

https://github.com/rackt/redux/pull/1291
