### ISSUE TITLE
componentWillReceiveProps happening immediately after loading only on mobile browsers

### ISSUE THREAD

**Issue by banderson5144** [rackt/redux#1210]
I am seeing an issue when I load a component that componentWillReceiveProps is being called almost immediately after. This is only happening on mobile browsers. On desktop I am not seeing this issue. Anyone else experiencing this?

**Comment by gaearon** [comment]
I don't see how this is related to Redux.

As this seems like a React usage question please ask it on StackOverflow. We try to reserve issues for feature and bug discussions.

If you ask it on StackOverflow please make sure to provide the relevant source code because it's impossible to help without knowing the details. It's even better if you can post a project reproducing the issue and the instructions to reproduce it.
