### ISSUE TITLE
Patching connect function

### ISSUE THREAD

**Issue by udnisap** [rackt/redux#1241]
I have certain set of mixins and other default props and dispatches that I want to map to all the dumb components via connect. Is there a way to do this with the framework other than monkey-patching the connect function?

**Comment by rossipedia** [comment]
What do you mean by "monkey-patching the connect function"? I'm not sure that's necessary. If I understand you correctly, you could just have a common connector function for your dumb components. The great thing about the design of react-redux is that it's just plain javascript, built on functional principles. 

Since `connect` returns a function that you apply to your components, you can just have a module called `dumbConnector.js` that just exports the result of a `connect` call, and you can apply that to whatever components you want.

**Comment by gaearon** [comment]
This is a usage question. Please ask it on StackOverflow.
This is not a support forum—it's an issue tracker.

This question is also not about Redux—it's about React Redux library.
It's unrelated to this repo.

When you ask it on StackOverflow please make sure to add more specifics because it's somewhat vague. Cheers!
