### ISSUE TITLE
Clarification: Immutable to json in react

### ISSUE THREAD

**Issue by udnisap** [rackt/redux#1242]
I am using the immutable in state but I was wondering if the react is used only to render using the state and since there are no mutations, we can easily get the json from the state at the top level after the reducers and pass so that we dont have to deal with the immutable getter methods. I will still use immutable in reducers but not on react.

Are there any side affects by doing this?

**Comment by ntkoso** [comment]
You will lose main benefit of Immutable, cheap `shouldComponentUpdate` check. 
To avoid getters situation in Components you can use [Immutable.Record](https://facebook.github.io/immutable-js/docs/#/Record).
Currently there are some quircks, but [Immutable.js 2016 Roadmap](https://www.facebook.com/notes/lee-byron/immutablejs-2016-roadmap/10153447836068757) includes improvements for Records.
Main difference is that instead of using `fromJS` you need to write your own rehydration/deserialization logic. [Example from Este](https://github.com/este/este/blob/master/src/common/todos/reducer.js#L11-L15).

**Comment by udnisap** [comment]
if im using the `PureRenderMixin` this is sorted out i guess. Or is it not? 
+1 for the Records. Will check that

**Comment by gaearon** [comment]
This would destroy the perf benefit of Immutable. `toJS()` is expensive and doing it upfront means too many allocations. Just don't use Immutable if you don't want to deal with it inside the components.
