### ISSUE TITLE
why use redux vs. functions that close over an immutable object?

### ISSUE THREAD

**Issue by EatYourSpinach** [rackt/redux#1252]
For the past few months the idea keeps coming to me that I can use reducers to create/track derived state; but it always ends up not working out, and I always come to the conclusion that my store should only store fundamental normalized state (api call results and aggregated user inputs).
If this is the case, and computed data is always computed after the fundamental store is updated, then why use redux at all? Why not just pass around methods that immutably update an object (which fires an event when updated)? 
Are there any cases where one would gain an advantage by having a fundamental store listen to actions pertaining to another piece of state? 
For example, lets suppose we have 2 concepts: items and selectedItems. Items come from an api call, selectedItems comes from the user. 
Having the items reducer physically store a 'selected' property on an item never ends up making sense to me. The fully materialized 'selectedItems' concept is a projection of 'items' and 'selectedItems (array of item ids)', which is created somewhere after redux. 
Sorry if this is the wrong place for this question, feel free to delete/close/redirect.

**Comment by gaearon** [comment]
>Having the items reducer physically store a 'selected' property on an item never ends up making sense to me. The fully materialized 'selectedItems' concept is a projection of 'items' and 'selectedItems (array of item ids)', which is created somewhere after redux. 

I'm not sure why you are equating storing "selected" field as a "Redux way" of doing things. In fact we recommend the opposite: store items and selectedIds separately. Strive to keep state denormalized.

>Why not just pass around methods that immutably update an object (which fires an event when updated)?

Sure, you can do that. You're giving up a few things though:

* If there is a mistake in the state update it's harder to find the function that modified the state because any component that has a cursor can do that. With Redux you *always* know the functions responsible for a specific part of state: these are reducers. If you log every action and state before and after, you can find which action causes the mistake, and at this point you know *the exact lines* where the mistake happened (corresponding switch case inside the corresponding reducer).

* If you don't have the concept of actions, you can't serialise them, save or send them. This rules out some scenarios of reproducing state mutation bugs. With Redux, you can record user actions and attach reproducible action scenarios with bug reports. The developers can then replay these actions to get the system into the same state.

If you don't care about these wins, sure, feel free to just use cursors. Not every app features mutations complex enough to warrant such mechanism as Redux and the idea of actions.

**Comment by gaearon** [comment]
>Strive to keep state denormalized.

Gah! I meant "normalized".

**Comment by EatYourSpinach** [comment]
Thanks for the reply Dan. I've been mentally resisting normalization, thinking I can maintain derived state on the fly from the stream of actions, but I see this is impossible!

**Comment by naw** [comment]
> Having the items reducer physically store a 'selected' property on an item never ends up making sense to me. The fully materialized 'selectedItems' concept is a projection of 'items' and 'selectedItems (array of item ids)', which is created somewhere after redux.

I think the above two sentences are orthogonal.  Storing a `selected` boolean property in the `items` array is not the same thing as storing a fully materialized `selectedItems` array, right?

At the risk of coming across as pedantic, I think it may be important to be clear on our terminology here as it pertains to each of these:

1. Storing a `selected` property on the main `items` array is _normalized_.  It is a perfectly acceptable non-redundant storage option for your store, although some people may prefer and recommend a different approach.

2. Storing a fully materialized `selectedItems` array with redundant `item` properties (like `itemName`) is _denormalized_.  This is _definitely_ discouraged.

So there are (at least) _two_ ways to store the data if you want to stay `normalized`:

a) `items` array and separate `selectedItemIds` array (just `id`'s)
b) `items` array with a `selected` boolean property on each item.

Does anyone disagree that these are both `normalized`?

Assuming not --- if official `redux` best practices prefer (a) over (b), that has more to do with "flatness" (i.e. not nested) rather than normalization.  Actually, a top-level property isn't really nested, so in this case, I'd have a hard time saying option (b) violates any best practices at all.  Perhaps you could clarify @gaearon ?

In the specific example @EatYourSpinach provided, it _does_ seem that option (a) is more closely aligned with how the server API and the client UI deliver data, so from a pragmatic standpoint, it's better than option (b) in this _particular_ case. The reducers have less "translation" work to do.

**Comment by gaearon** [comment]
Yeah, @naw gets my point across better than I do!

The only thing I'd add is I would optimize for ease of writing local mutations as opposed to ease of initial data hydration. Local mutations are more complex so I would design the state structure based on what makes it easier to write reducers changing that data (assuming it ever changes!) and only later take the server loading transformations into account. This is why in this particular example I'd say `selectedIds` win over `item.selected`—it seems simpler to manage and update selection information separately from the data information, and give it a dedicated reducer. However of course this is not a hard rule, and you should always consider each case on an individual basis. Finally, @naw is right the only approach we downright reject is storing something like `selectedItems` in state because this is basically data duplication.

**Comment by slorber** [comment]
In my experience it's preferable to keep backend payloads unmodified on the frontend. If local view modifications related to an item should be made then store it somewhere else and not in the payload. If you want to "refresh" the payload and you have a new "selected" attribute, then you might loose it (or would have to code some annoying merge strategy)

@gaearon selectedItems is it really data duplication? Duplicating references or ids does not seem such a big deal in term of memory (until you have multiple references to the same item :p)

**Comment by johanneslumpe** [comment]
@slorber It requires more work when re-loading data from the api, as the `selectedItems` array also has to be re-populated with the updated documents whereas we won't have that issue if we just keep ids.

**Comment by slorber** [comment]
yes @johanneslumpe  that's why I said "until you have multiple references to the same item" :)

**Comment by johanneslumpe** [comment]
@slorber But has soon as you have a `selectedItems` array you have multiple references ;) Even then they're not a problem in terms of memory, just a pain in the butt.

**Comment by sompylasar** [comment]
@slorber if the state gets serialized and then deserialized, then there is no common reference to the same object, instead there are two collections of different objects.

**Comment by johanneslumpe** [comment]
@sompylasar good point!
