### ISSUE TITLE
Design difference towards the original Flux dispatcher - possibility of dispatch loops in Redux ? 

### ISSUE THREAD

**Issue by jhades** [rackt/redux#1266]
Hello, I've noticed an important design difference towards original Flux, I think an important feature of Flux is missing in Redux but could be easily fixed. 

in the original Flux dispatcher, the dispatchOngoing flag was set to false only at the end of the dispatch, take a look [here](https://github.com/facebook/flux/blob/master/src/Dispatcher.js#L194).

This means that all the the dispatch listeners (the Stores) will be given the occasion of reacting to the dispatch, but while doing so they cannot dispatch an action themselves. This would cause actions to be dispatched in chain which is one of the main things that Flux tries to avoid, to keep the application simple to reason about.

That scenario that Flux tries to avoid is sometimes known as "event soup", and it happens a lot in applications that rely on event buses or similar, where events get chained in unexpected ways, sometimes get triggered multiple times without the developer realizing it, specially when dispatches are triggered inside if clauses.

Avoiding this looks like one of the main goals of Flux based on the original presentation, have a look [here](https://youtu.be/nYkdrAPrdcw?list=PLb0IAmt7-GS188xDYE-u1ShQmFFGbrk0v&t=1075). Another reference is made [here](https://youtu.be/nYkdrAPrdcw?list=PLb0IAmt7-GS188xDYE-u1ShQmFFGbrk0v&t=1157):

> The dispatcher is the central traffic controller of the system. It ensures that while an action is ongoing, neither the stores nor the view or any other part of the system can trigger another action

Currently in Redux, we can see the following code ([here](https://github.com/rackt/redux/blob/master/src/createStore.js#L126)):

    if (isDispatching) {
      throw new Error('Reducers may not dispatch actions.')
    }

    try {
      isDispatching = true
      currentState = currentReducer(currentState, action)
    } finally {
      isDispatching = false
    }

    listeners.slice().forEach(listener => listener())
    return action

The isDispatching flag is set to false *before* the listeners are called. 

This allows a listener to trigger another action, which means that the unintended action chains that Flux is trying to avoid are actually possible in Redux. 

I would  propose calling the listeners while the dispatch is still ongoing to avoid this issue and align Redux with this important Flux feature. I believe its a safety mechanism that will result in more maintainable Redux apps in the long run. Let me know if it makes sense, thx

**Comment by gaearon** [comment]
We decided early on to not protect against dispatch loops. Sure, they are an anti-pattern but I've found I had to resort to them more than a few times in React app (e.g. navigation as action -> component mounting -> gotta load some data!)

In vanilla Flux this quickly becomes an exercise in wrapping initial data fetching calls in setTimeout and different parts of code start breaking each other because of slight changes in which components are mounted under what circumstances. After 8 months of using Flux I have never experienced a single case where "dispatch in the middle of dispatch" error actually saved me from a mistake rather than just being a nuisance.

There is also an important technical reason why Flux has to have this warning. Flux stores fire listeners while dispatch is still ongoing. If Flux allowed additional dispatches during that time, the app would get into an inconsistent state where some stores have new data, and some stores have outdated data, and they are receiving yet another action. By constrast, in Redux there is a single store, so by the time the subscribers are called, all state has been updated with the new action, so the app stays consistent.

This is a practical tradeoff I chose to make based on my experience and I understand if you disagree with it. However I found it more practical than what Flux offered, and we could pull it off due to a slightly different architecture than Flux had.

**Comment by jhades** [comment]
Thanks for the quick response, I imagined there was a reason behind it, but could not find it mentioned anywhere so thought it would be good to raise it here.

Yes I see what you mean with the setTimeout, in my case I've seen two apps where this type of event carousel was a real issue: multiple persons maintain an app over time and add events, modify events etc. One day we put a breakpoint in an event and its being hit 5 times instead of one and nobody knows why (because of chains of events), and its hard to change it. It could have been just bad luck, but i've seen it popup in separate projects.

So that's the reason why Flux looked such a good idea, and the dispatch protection mechanism a good way to prevent such issues. 

But if in practice if the protection mechanism causes more issues than it solves, indeed might as well not include it.

Probably the most important to avoid the issue ("event soup") it is to be aware of it, rather than relying on some implicit protection mechanism that can be easily circumvented (with setTimeout() for example). OK again thanks for the clarification

**Comment by gaearon** [comment]
>Yes I see what you mean with the setTimeout, in my case I've seen two apps where this type of event carousel was a real issue: multiple persons maintain an app over time and add events, modify events etc. One day we put a breakpoint in an event and its being hit 5 times instead of one and nobody knows why (because of chains of events), and its hard to change it. It could have been just bad luck, but i've seen it popup in separate projects.

I totally understand this situation with events, but I didn’t have this problem with Redux actions. Firing an action in a lifecycle hook is an escape hatch and I didn’t see people doing this more than once and going into some kind of chain.

>Probably the most important to avoid the issue ("event soup") it is to be aware of it, rather than relying on some implicit protection mechanism that can be easily circumvented (with setTimeout() for example). OK again thanks for the clarification

Yes.
