### ISSUE TITLE
a take on making sagas easier to grok

### ISSUE THREAD

**Issue by ianstormtaylor** [rackt/redux#1280]
After diving into Redux, I've been reading through all of the issues that discuss handling async effects. It seems like [`redux-saga`](https://github.com/yelouafi/redux-saga) has been the most championed idea on that front. But there's still talk of canonicalizing an "official" way to do side effects that's easier to grok, since the learning curve for `redux-saga` is still really steep. 

I figured I'd throw something here that might be useful, or might be complete non-sense...

Here's an example, of what a current saga implementation might look like:

```js
import fetch from 'isomorphic-fetch'
import * as actions from '../actions'
import { call, fork, take, put } from 'redux-saga'

/**
 * Users saga.
 *
 * @param {Function} getState
 */

function* users(getState) {
  yield fork(get, getState)
  yield fork(create, getState)
  yield fork(update, getState)
  yield fork(remove, getState)
}

/**
 * Get a user by `id`.
 *
 * @param {Function} getState
 */

function* get(getState) {
  while (true) {
    const action = yield take(actions.USER_GET)
    const { id } = action

    const state = getState()
    const user = state.api.users[id]
    if (user) return yield put(actions.getUserResolve(user))

    const res = yield call(fetch, `/users/${action.id}`)
    const json = yield res.json()
    const next = res.ok ? actions.getUserResolve : actions.getUserReject
    yield put(next(json))
  }
}

/**
 * Export.
 */

export default users
```

Which by itself is not bad, but there are a series of things that make it tricky to understand what's going on coming fresh from Redux:

- The concept of `fork` and others can be confusing.
- Having to indirect things through `call`, `apply`, and `cps` makes things awkward.
- The need to `take` and `while (true)` adds extra boilerplate, and requires learning the internals.
- Using `put` is a new unfamiliar term, instead of `dispatch`.

I was thinking, if the above example is possible, it doesn't seem far off to get to something a little bit terser, with fewer new concepts to explain, and a bit more "Redux-like"...

```js
import fetch from 'isomorphic-fetch'
import * as actions from '../actions'
import { createSaga, wrap } from 'redux'

/**
 * Wrap for testability.
 */

fetch = wrap(fetch)

/**
 * Get a user by `id`.
 *
 * @param {Object} action
 * @param {Store} store
 * @return {Object}
 */

function* get({ id }, { dispatch, getState }) {
  const state = getState()
  const user = state.api.users[id]
  if (user) return yield dispatch(actions.getUserResolve(user))

  const res = yield fetch(`/users/${id}`)
  const json = yield res.json()
  const next = res.ok ? actions.getUserResolve : actions.getUserReject
  yield dispatch(next(json))
}

/**
 * Export.
 */

export default createSaga({
  [actions.USER_GET]: get,
  [actions.USER_CREATE]: create,
  [actions.USER_UPDATE]: update,
  [actions.USER_REMOVE]: remove
})
```

The changes are basically:

- Change `call` to be a transparent `wrap` helper instead, which is easy to add/remove.
- Pass in store-like `{ dispatch, getState }` for familiarity.
- Allow for sugar with `createSaga` to remove boilerplate.

Which (I think?) gets it a lot closer to being simple to explain to newcomers—a way to have long-running processes observe specific actions and run async effects.

There's a chance I completely misunderstood how Sagas work, and something in there isn't possible. If so, feel free to close. But I figured I'd drop this here since others have been thinking about how to canonicalize async effects, and make them as simple as possible to integrate into the Redux mental model.

**Comment by gaearon** [comment]
cc @yelouafi

**Comment by timdorr** [comment]
Shouldn't this be on the redux-saga repo instead? 

My two cents: I don't think there's ever going to be an official effects system for Redux. Namely because there are tradeoffs with every proposal so far. They're a getting really good, but some are better at certain things than others, so one choice might not be the best for all use cases. I'd rather have the "official" nature of a library come from its popularity and quality, rather than someone dictating what they should do. Basically, laissez-faire :smile:

**Comment by gaearon** [comment]
I am leaning this way too. Up to the point where I'd create `async-sagas`, `real-world-sagas` examples just to show the difference in a approaches. That and an official recipe on using sagas as alternative async model could help IMO.

**Comment by yelouafi** [comment]
>Shouldn't this be on the redux-saga repo instead?

Yes I think so

@ianstormtaylor using `wrap(fetch)` you should repeat this with every api service you call. `call` gives a generic way to do this.

initially I implemented all api calls as redux actions so you'd be dispatching effects as actions. It turned out that this solution wasn't really practical. Because you'd have also to create a custom action constant/action creators which is a lot of boilerplate (people are already complaining about the boilerplate of *normal* actions).

I used put because it sounded symmetrical to take. The lib is also inspired by [CSP] https://en.wikipedia.org/wiki/Communicating_sequential_processes. Using dispatch would put some confusion because w're not calling the dispatch function just creating an effect description (consider it like a shortcut to call(dispatch, action) so you don't have to worry about passing dispatch to your sagas).

as for createSaga, you're firing the control flow (Sagas) on each incoming action; redux-saga considers incoming actions themselves as part of the control flow. It allows to implement logic that spans accross a sequence of multiple actions.

**Comment by yelouafi** [comment]
>They're a getting really good, but some are better at certain things than others, so one choice might not be the best for all use cases

@timdorr agree 100%. There is no one fit-all paradigm for all possible use cases. For some situations ELM like solutions like redux-loop seems more appropriate (esp. when there is 1-1 mapping between the state shape and effects). Some use cases are better handled by Reactive Streams like Rx.

**Comment by gaearon** [comment]
Thanks for your input!

**Comment by ianstormtaylor** [comment]
Thanks for replying @yelouafi! I'm aware of a few of the things you mentioned:

- `createSaga` definitely isn't as feature-full as the top-level generator, that's why it's sugar. But for cases where you want to do things across actions, you'd want less of the sugar. You could imagine a case where `createSaga(gen, gen, gen)` would be one-level removed, firing for _any_ action. And just regular `*saga` would be the current top-level with full functionality. Very similar to how `combineReducers` helps you eliminate boilerplate. It's not firing the control flow on each incoming action, it's composing the control flow from multiple more focused controlling functions.

- `wrap` you have to use with every method, but it results in code that's readable instead of having to muddy up the source with `call`. You could still choose to `call` if you really wanted to, but most of the cases are for things like `fetch` or `readFile`, where just wrapping a few methods gets you the testability without having to make each invocation harder to parse.

I think that `redux-saga` as currently implemented, and evidenced by the [real-world example](https://github.com/yelouafi/redux-saga/blob/master/examples/real-world/sagas/index.js), has way too much indirection for the common case, resulting in lots of boilerplate. Basically just trying to start conversations that aim to get rid of boilerplate, and move towards something that's actually useable without lots of configuration, but that's okay for it to not be here.

**Comment by ianstormtaylor** [comment]
Just in case anyone was curious about this kinds of conveniences, here's the code to make the cleaned up example possible: https://gist.github.com/ianstormtaylor/84f3529e218d381a54cc
