### ISSUE TITLE
Object rest spread suggestion in Troubleshooting is outdated for babel@6

### ISSUE THREAD

**Issue by jmm** [rackt/redux#1292]
This suggestion / link in [Troubleshooting](http://redux.js.org/docs/Troubleshooting.html) is outdated with respect to Babel 6:

> You can also enable [ES7 object spread proposal](https://github.com/sebmarkbage/ecmascript-rest-spread) with [Babel stage 1](http://babeljs.io/docs/usage/experimental/):

PR incoming.

**Comment by timdorr** [comment]
Closing in favor of the discussion on the PR.

**Comment by jmm** [comment]
@timdorr The only reason I opened this issue is because of the first bullet point in [`CONTRIBUTING > Submitting Changes`](https://github.com/rackt/redux/blob/64a489bf2d97d0e7c125d6142da4da57aed400ce/CONTRIBUTING.md#submitting-changes):

> Open a new issue in the Issue tracker.

Is it unnecessary to follow that workflow, or do you just call it on a case by case basis?

**Comment by timdorr** [comment]
It's mainly meant for there to be some initial discussion on the issue, usually around the validity of the report and any possible solutions to look into. Since Github treats issues and PRs fairly interchangeably, opening up one of each around the same time means we'd be splitting the discussion in two. It's best if we centralize things in one place so no feedback or ideas get lost.
