### ISSUE TITLE
New isomorphic example with v1.0.0-rc syntax

### ISSUE THREAD

**Issue by coodoo** [rackt/redux#315]
I just released a new [isomorphic example](https://github.com/coodoo/react-redux-isomorphic-example), would appreciate any code review, thanks.

Will send a PR for that.

**Comment by ViniciusAtaide** [comment]
Tip: use attribute initializers in your JS/API/shop. They're awesome :)

**Comment by gaearon** [comment]
The reducers in your code are mutating the state. They are also mutating action payload.
I'll file an issue.

**Comment by gaearon** [comment]
Adding `docs` label so I don't forget to document these anti-patterns.

**Comment by gaearon** [comment]
Filed as https://github.com/coodoo/react-redux-isomorphic-example/issues/9.

**Comment by coodoo** [comment]
Thanks for the detailed instructions, it's been very helpful and now the example is fully updated.

**Comment by gaearon** [comment]
I'll keep this open because I want to document these problems better.

**Comment by davezuko** [comment]
Rather than opening up a new thread, I wanted to throw my hat into the ring as well: https://github.com/davezuko/react-redux-starter-kit . Not perfect yet but trying to give people an example of how to use both 1.0.0 candidates for Redux and React Router in conjunction.

If this should be in its own issue let me know, I just wanted to avoid polluting the issue list.

**Comment by gaearon** [comment]
Now documented in http://rackt.github.io/redux/docs/Troubleshooting.html.
