### ISSUE TITLE
Investigate DataScript

### ISSUE THREAD

**Issue by gaearon** [rackt/redux#318]
I don't know much about [DataScript](https://github.com/tonsky/datascript) but I've only heard great things about it.

Therefore my questions are:

* Does it replace Redux, or is it orthogonal?
* Would you ever want to mix them?
* Can a Redux app offload some of its data management to DataScript?
* Can [Redux devtools](https://github.com/gaearon/redux-devtools/) be made to work with DataScript under the hood?
* Is there a place for “DataScript-Redux” adapter?

**Comment by ehd** [comment]
Really interesting question, and maybe should be looked at in connection with "flux over the wire" or "universal actions".

@jlongster did interesting things with redux and DataScript here: https://github.com/jlongster/redux-experiments

> Does it replace Redux, or is it orthogonal?

Not all actions are necessarily state changes. DataScript transactions are strictly either additions or retractions of datoms (entity-attribute-value tuples). Redux actions probably often result in direct additions or retractions of datoms, but they wouldn't have to. Therefore I think they're orthogonal.

**Comment by skrat** [comment]
I can see how you can use DS's `create-conn` (which really just gives you a ClojureScript's `atom`) as initial state, then reduce over that. Looks like the simplest use case to me.

So to answer: it doesn't replace Redux, it can provide the state object. I'm not yet familiar with Redux, but I think one can use anything she wants as a state object, eg. plain JS object/array, mori, Immutable.js, DataScript, etc.

**Comment by nbostrom** [comment]
... Or just a part of the state object as the domain layer?

```javascript
{
  db: <DSDataBase>,
  viewState: <Object>
}
```

**Comment by jlongster** [comment]
I'd say it's somewhat orthogonal. When your state is a graph, you need a DB like DataScript or GraphQL. When it's just a tree, which most of your UI state is going to be, you don't need it. I don't really see much point in mixing them, as then you have to handle two different types of objects when wanting to snapshot or replay.

**Comment by nbostrom** [comment]
True, it would indeed add complexity... Though I see a lot of value in having a database on the client that saves patches/transformations by monotonic ids like datalog does (and Meteor and any other lib based on CRDTs or Gossip or similar.). This makes syncronization after working offline very doable. What I find very interesting about Datascript and what set it apart from the others is that the database is immutable and easy to reduce over, which you have clearly demonstrated in your experiment. At the same time I see value in having UI state in pure objects. Do you mean that the UI state could also go in the DB? Or should the DB be entirely separated from the UI state?

**Comment by jlongster** [comment]
I was thinking that if you already have a DataScript db, you would store UI state it in as well (maybe with an alternative interface, like faking local state in it). But I don't really know, you'd need to try to build something with it and see. Some people in CLJS land already have Meteor-like things with DataScript that also store UI state. I need to do more research to contribute anything else though.

**Comment by jiyinyiyong** [comment]
Maybe @tonsky ?

**Comment by nbostrom** [comment]
@jlongster, cool! I played around with something a while ago as a replacement for Immstruct (the datalayer for Omniscient) using scuttlebutts here https://github.com/nbostrom/humdrum. I would like to have something like this for redux apps. My only gripe with DataScript is that its 367K minimized, because cljs. :/

**Comment by vladap** [comment]
Is it Datomic but for a browser? If yes, give it to me:)

**Comment by gaearon** [comment]
I'm closing as there appears no significant interest.

**Comment by mkunikow** [comment]
Sample redux datascript integration
https://github.com/jlongster/redux-experiments

**Comment by hden** [comment]
@gaearon I made a simple todo app with redux, redux-undo, and datascript.

Overall I think it's a quite pleasant experience.

1. Since the state is managed by a transactional database, the reducer is much cleaner. [before](https://github.com/rackt/redux/blob/master/examples/todos-with-undo/reducers.js#L7-L56) [after](https://github.com/hden/reduxscript/blob/master/reducers.js#L7-L23)
2. With a datomic query language, the component describe what it want's, similar to om.next. [before](https://github.com/rackt/redux/blob/master/examples/todos-with-undo/components/Todo.js#L7-L12) [after](https://github.com/hden/reduxscript/blob/master/components/Todo.js#L7)
3. As with all clojure data types, the datjscript DB instances are immutable, making it quite easy to manage history and state equality [before](https://github.com/rackt/redux/blob/master/examples/todos-with-undo/reducers.js#L40-L43) [after](https://github.com/hden/reduxscript/blob/master/reducers.js#L12-L13).
