### ISSUE TITLE
Add example: url router as yet another reducer

### ISSUE THREAD

**Issue by gbezyuk** [rackt/redux#452]
This issue is probably worth a separate subproject, but still I'll write down my thoughts here for now.

First, there are barely any web applications that have no routes. For this reason, I think redux should give some recommendations or examples on how to implement it.

There are solutions like react-router, which seem totally wrong in a flux/redux environment to me. Router shouldn't be a component, it should be implemented as a reducer instead. Maybe some helpers will be required, but still the point is in thinking about current route as just another part of an application state, stored in redux.

I'm thinking about writing my own implementation, but I'm not sure that I'll have enough time and motivation. So I decided to share this idea here just in case.

**Comment by mushishi78** [comment]
If it helps, I read this [thread](https://github.com/acdlite/redux-react-router/issues/1) and decided to go with [reactive-router](https://github.com/christianalfoni/reactive-router).

**Comment by gaearon** [comment]
React Router will be fine soon. :-)

In 1.0, the [history implementation](https://github.com/rackt/history) is separated so it's no longer mixing concerns. The `<Router>` component in 1.0 can accept all state as a prop, instead of subscribing to history itself, so again, you can store its state in Redux tree.

Definitely watch out for https://github.com/acdlite/redux-react-router/issues/1, as whatever official solution we'll come up with, will most probably end up there.

**Comment by gaearon** [comment]
Let's track routing in https://github.com/rackt/redux/issues/177.
