### ISSUE TITLE
Make README friendlier to people outside React/NPM/Webpack/Browserify ecosystem

### ISSUE THREAD

**Issue by gaearon** [rackt/redux#563]
Some recent feedback:

1. It's not clear how what problem a "state container" solving in a real app
2. It's not clear how to go from `npm install redux` to running even the README gist (where to paste it?)
3. The README gist is slightly misleading, as it doesn't show any hint at a possible view layer
4. People really like https://github.com/jackielii/simplest-redux-example

Let's not forget there are many people outside Browserify/Webpack/NPM bubble, and we want to help them get started.

**Comment by gaearon** [comment]
This might be a first step towards helping people get started: https://github.com/rackt/redux/commit/79c76a617214471d4f84ee5fa8e9c5086b303916

**Comment by octref** [comment]
I'm just walking through the 2.Basics example. Two points:
1. You never mentioned how you should compile the code.
2. You can be more specific about how to make the Chrome debugger output in 2.3 Stores.

I'm using `browserify index.js -t babelify -o bundle.js`.

I think a minimal hello-world example which contains not much logic (not even a counter), but just gets everything working together (npm install everything required, how to CLI compile, how to gets webpack working), would be very helpful.

**Comment by octref** [comment]
BTW, I think you should include a short explanation of how Webpack+Redux work together in the tutorial. Developer features like time-travel and hot-reload are a selling point of redux, and without Webpack you can't do these(or can you?).

**Comment by vincentfretin** [comment]
@octref For hot reloading with browserify I use https://github.com/Kureev/browserify-react-live It works great!

**Comment by cesarandreu** [comment]
I made a [boilerplate](https://github.com/cesarandreu/web-app) for web apps that provides production and development builds, testing environment, source-maps, index.html generation, css extraction, and hot-loading. Only uses npm scripts, no need for complicated task runners. It also includes file loader for managing other assets (i.e. images, fonts), which you'll generally have a few of in your app. In production builds, it'll do cache busting of all your assets. Realistically, it's the bare minimum environment for a production-ready SPA.

If there's any interest, I could fork it and include redux, routing (using react-router + redux-react-router), and redux-devtools (in development). It might be good to have a project generator, similar to what you get when you use `rails g app`, which lets you start building real apps from the get-go.

**Comment by octref** [comment]
@cesarandreu 
I think the problem is a lof of redux's audience might come from React community, and as you don't really gain much for using ES6 with React, many React devs still default to ES5.
So for @gaearon 's problem 2 I think adding some instruction, like
```
// To run this example:
// - Save it in a file index.js
// - `npm install redux`
// - `npm install --global babel` to install babel
// - `babel index.js -o compiled.js` to compile ES6 to ES5
// - `node compiled.js`
```
What you describe sounds great, and I think you can put it into something like a starter-kit or project-generator, but from his description "go from npm install redux to running even the README gist" your project seems a overkill.

**Comment by Medros** [comment]
I have to second some of the notes here. I'm still on the early stages of understanding ES6 so I've been searching for more ES5 examples. Also since we don't use webpack/browserfy in our environment it gets hard to know that you have to convert the src files to run. We use require so I have to wrap all files with a define so that exports and module is defined.

**Comment by gaearon** [comment]
>Also since we don't use webpack/browserfy in our environment it gets hard to know that you have to convert the src files to run.

We have a cdnjs build.

https://cdnjs.cloudflare.com/ajax/libs/redux/1.0.1/redux.js
https://cdnjs.cloudflare.com/ajax/libs/redux/1.0.1/redux.min.js

You'll still need additional libraries like `react-redux`, `redux-thunk` etc and it's a lot easier to consume them from NPM.

**Comment by mindjuice** [comment]
>Developer features like time-travel and hot-reload are a selling point of redux

I agree with this.  I was thinking that the official examples should have the devtools included.  Cloning TodoMVC or Counter or the Real World example and playing with the time travel debugger (with the slider) would be quite compelling IMO.  Was this left out intentionally to keep the examples simpler?

Maybe at least the Real World example could include it since we do debugging in the real world.

**Comment by gaearon** [comment]
Just added a note on npm in README:

https://github.com/rackt/redux/commit/6a4d9f0b05f01be1050d569d79a91e416150d5a6

**Comment by gaearon** [comment]
Closing as I currently don't have resources to pull off a complete tutorial, and there are plenty basic Redux examples we link to from the docs. I will be working on a screencast series complementary to the tutorials from docs, which will be done in JSFiddle, so that would help the beginners.

**Comment by octref** [comment]
@gaearon 
Hey, just wondering if you had time to pull off the screencast series.  
I think I can write a tutorial if it's still needed.

**Comment by gaearon** [comment]
@octref 

I made 5 lessons today, hopefully will make 3 lessons tomorrow.
They'll be available on Egghead early next week.
I'll tweet if they're up.

**Comment by octref** [comment]
@gaearon 
Hey, I just took a look at Egghead, and it seems some "pro" videos are only available through subscription.
Will you release your lessons as free or not?

**Comment by gaearon** [comment]
I intend the “basics” series I'm (still) working on to be free.

**Comment by gaearon** [comment]
FWIW the Egghead series was released: https://egghead.io/series/getting-started-with-redux
And we just added a vanilla example that doesn't use React, Webpack, or npm: https://github.com/rackt/redux/pull/1289

Hope it helps!
