### ISSUE TITLE
Installation via Bower

### ISSUE THREAD

**Issue by asiniy** [rackt/redux#579]
Hey there!

I am bower user and I want to install redux using my bower manager. How can I do it?

**Comment by timdorr** [comment]
You can't. Redux isn't packaged like a component (nor does it really behave like one). You should use npm and something like webpack or browserify to make `require()` available. Bonus points for using babel.

**Comment by gaearon** [comment]
@timdorr  This is not quite right. There _is_ a standalone build of Redux. It's even [available on cdnjs](https://cdnjs.com/libraries/redux) (we should document that).

@asiniy I'm up for supporting Bower if there is enough interest in it. But Redux is usually used with many other small packages, and since they are all on NPM, I don't think it's likely you'll persuade their maintainers to also provide Bower versions. In the long run it's easier for everyone to just use NPM.

If you absolutely can't use NPM, [grab the pre-built file from cdnjs](https://cdnjs.com/libraries/redux) and put it in your `vendor` folder.

**Comment by timdorr** [comment]
Oh, my bad. Didn't even know. 

In that case, you can manage downloading via Bower. Just put the cdnjs URL as the version for your dependencies.

```json
  "dependencies": {
    "redux": "https://cdnjs.cloudflare.com/ajax/libs/redux/1.0.1/redux.js",
  },
```

**Comment by asiniy** [comment]
@timdorr, thanks for code.

@gaeron other small packages (jquery, react) are placed on the Bower too ;)

**Comment by lapanoid** [comment]
@asiniy If you call jquery, react "small packages" then yes =)

**Comment by asiniy** [comment]
@lapanoid what do you mean by small packages?

**Comment by gaearon** [comment]
>@gaearon other small packages (jquery, react) are placed on the Bower too ;)

In my original message:

>But Redux is usually used with many other small packages, and since they are all on NPM

I didn't mean to call React or jQuery small :-).

I'm referring to many other packages related to Redux:

* https://github.com/gaearon/redux-thunk
* https://github.com/acdlite/redux-promise
* https://github.com/fcomb/redux-logger
* https://github.com/gaearon/redux-devtools

etc

**Comment by redexp** [comment]
You will ignore a huge community of frontend package managers?

It's so frustrating when I can't find pre build version in repo. You already prepared webpack config, is it so difficult to make `dist/redux.js` and `dist/redux.min.js` like everybody else?

When redux will become more popular, someone will create fork of this repo and will add it to bower (as always).

**Comment by gaearon** [comment]
>It's so frustrating when I can't find pre build version in repo. You already prepared webpack config, is it so difficult to make dist/redux.js and dist/redux.min.js like everybody else?

I wrote above that the built code is available:

https://cdnjs.cloudflare.com/ajax/libs/redux/1.0.1/redux.js
https://cdnjs.cloudflare.com/ajax/libs/redux/1.0.1/redux.min.js

Instead of writing this comment you could've taken time to edit the README to include the links to them, and sent a PR. Just sayin'

**Comment by gaearon** [comment]
[Using Bower is a bad idea.](http://gofore.com/ohjelmistokehitys/stop-using-bower/) If you use Bower and want to fork the repo, please do it, but we won't support it. I explained above that it makes little sense with Redux's ecosystem because most of complementary packages are small and are all on NPM.

We also won't put build products into Git repo. Otherwise every second new PR will contain changes to the built files, because people will keep doing this.

**Comment by gaearon** [comment]
Hope this helps: https://github.com/rackt/redux/pull/630
This is what you could do instead of writing a rant.

**Comment by gaearon** [comment]
To sum up this thread:

1. We won't support Bower and won't change this decision for [reasons](https://github.com/rackt/redux/issues/944#issuecomment-150777085).
2. `bower install https://cdnjs.cloudflare.com/ajax/libs/redux/3.0.4/redux.js` if you need to
