### ISSUE TITLE
Example for an undo/redo feature within examples, maybe the todomvc

### ISSUE THREAD

**Issue by mlusetti** [rackt/redux#599]
It would be nice to see an example for undo/redo features in one of the examples that comes with redux.

So we could also have an example for  a high order reducer.

**Comment by FredyC** [comment]
I am struggling with undo/redo feature right now (gaearon/redux-devtools#113). It is basically high order reducer. I am currently trying to figure out the way how to make undo/redo part of the state itself instead of keeping it somewhere outside. 

I had found out that devtools is not only reason, it still need to change something in the state, so "smart" component can decide about update for eg. showing proper state of undo button based on availability of a history.

Big problem here is the `combineReducers` which is run after my high order reducer stores information about transitions (next / previous) to the state. This is thrown away as new state with only known store slices is created.

I am most probably missing some obvious solution because from the nature of Redux it should be really easy to do something like this :(

**Comment by FredyC** [comment]
Sigh...when I think that I've got solution, something else gets wrong. Currently I pretty simple regular reducer (that gets into `combineHistory`) like this.

    export function tgHistory(state, action) {
        return state || {
            action: null,
            undo: null,
            redo: null,
        };
    }

And the high order reducer does this.

        function record(state, action) {
            const nextState = {
                ...state,
                tgHistory: {
                    action,
                    undo: state,
                    redo: null,
                }
            };
            state.tgHistory = {
                ...state.tgHistory,
                redo: nextState,
            };
            return nextState;
    }

I don't like it much, especially the part about mutating the previous state to add pointer to the next one. And very same spot is also a problem for the chibicode/react-json-tree which does `deepEqual` in its `shouldComponentUpdate` and this recursive object is causing **stack overflow** :(

Recording just the next state for undo operation is obviously easy, but once I trigger UNDO action, I need to know there is state for the REDO action. I am somewhat clueless on this.

**Comment by FredyC** [comment]
Oh my, after such struggle I've found this gem :) https://gist.github.com/gaearon/2b3ee315bb6a3b280b7c. Thanks @iclanzan !

**Comment by gaearon** [comment]
Check this out:

https://github.com/omnidan/redux-undo
https://github.com/omnidan/redux-undo-boilerplate

**Comment by gaearon** [comment]
cc @omnidan — would you like to contribute an `undo` example to the `examples` folder? I'm not sure what it should be about — counter seems too simple, adding it to `todomvc` might confuse people.

I'd probably add another todo example based on [this tutorial](http://rackt.github.io/redux/docs/basics/ExampleTodoList.html) without todomvc styling—keep it plain. Since it already keeps `visibilityFilter` in Redux state, it would be interesting to demo undoing a *part of the state*—i.e. undoing adding/editing/removing todos but without affecting the selected visibility filter.

**Comment by omnidan** [comment]
@gaearon I can do that :+1: I'll use the tutorial as a base for my code

**Comment by omnidan** [comment]
@gaearon please let me know if I should use my `redux-undo-boilerplate` or keep it plain and simple?

**Comment by FredyC** [comment]
It might also interesting for this example to see how to implementation of Undo/Redo buttons which would be disabled when there is nothing in the history. I've already mentioned in [redux-undo](https://github.com/omnidan/redux-undo/issues/7) repo.

**Comment by gaearon** [comment]
@omnidan Better a separate project based on [this example](http://rackt.github.io/redux/docs/basics/ExampleTodoList.html) (it's not currently in `examples` directory so I think it's a fairly good choice)

**Comment by omnidan** [comment]
@gaearon Alright, I'll work on that then :+1:

**Comment by omnidan** [comment]
@gaearon done in https://github.com/rackt/redux/pull/777 :3

**Comment by gaearon** [comment]
Superseded by #777.
