### ISSUE TITLE
Solution for simple action creation without string constants and less magic 

### ISSUE THREAD

**Issue by grigory-leonenko** [rackt/redux#628]
I was little annoyed by string constants as action types. And write solution for this, need for objective criticism and ideas. The solution is create action as class methods, and make method name accesible. 

```js
@EasyActions
class Actions {
   USER_ACTION(type, id){
        return {type, id}
   }
}
export default new Actions(); 
---
import Action from './actions';

dispatch(Actions.USER_ACTION(42))

switch(action.type) {
   case Actions.USER_ACTION:
       // return state
}

```

More info and examples here: https://github.com/grigory-leonenko/redux-easy-actions

**Comment by gaearon** [comment]
Indeed, you may do this if you like it better.
See also:

https://github.com/acdlite/redux-actions
https://github.com/insin/redux-action-utils

http://rackt.github.io/redux/docs/recipes/ReducingBoilerplate.html#actions
http://rackt.github.io/redux/docs/recipes/ReducingBoilerplate.html#generating-action-creators

**Comment by grigory-leonenko** [comment]
Thanks. I explore this solutions before. But i wanted to keep action creators as plain function without any magic.

**Comment by joebadmo** [comment]
@gaearon It seems to me that the types as strings allow for a lot of opportunity for error, and action type constants are a lot of unnecessary boilerplate. I really like redux, it seems like a distillation of all the good parts of "canonical" flux, but dispatching actions by strings seems like another vestigial thing from canonical flux that isn't really necessary.

I also like the direction @grigory-leonenko is going. We've actually implemented our own flux-ish singleton store on top of baobab, and we've come to a lot of the same conclusions that redux has. However, we did get rid of dispatching by strings and replaced them with simple function calls.

We have an "actions definition" object where we define the equivalent of reducers:

```
let actions = {
  setFoo(context, payload) { ... },
  setBar(context, payload) { ... }
};
```

These definitions get partially applied with the appropriate context and the store exposes the partially applied functions on its `actions` property:

```
let store = new Store({ initialState, actions });
store.actions.setFoo('baz');
```

This has the nice property of not relying on string constants to match on, and not having to define/bikeshed over the name of the property to match on, or to have to handle actions that don't match on a type. Misspellings generate a simple 'not a function' exception.

We've actually gone a bit further than this, too. To solve the issue of "name-spacing", e.g. inventing a naming scheme for actions on large store with action types having names like "FOO:BAR:INCREMENT" or whatever, we instead allow the action tree to mirror the shape of the state tree:

```
let initialState = {
  foo: {
    items: []
  },
  bar: {
    items: []
  }
};

let actions = {
  foo: {
    items: {
      addItem(context, payload) {
       return context.getState().concat(payload);
      }
    }
  }
};
```

In this example, `context` is the "path" to the function in action tree (`foo.items` here).

You can see the obvious opportunity for composing a reducer into the two separate namespaces.

This also gives us nice, namespaced access to the actions:

```
store.actions.foo.items.addItem({ id: 0 });
```

I'm investigating replacing our own store implementation with redux, and I'm leaning toward doing it anyway, but these are some ergonomic niceties we've enjoyed in our implementation that I would love to see (or something similar) in redux. The implementation would be fairly trivial, but it is a pretty significant departure from the current redux api.

In any case, I appreciate any feedback. Keep up the great work!

**Comment by gaearon** [comment]
>I really like redux, it seems like a distillation of all the good parts of "canonical" flux, but dispatching actions by strings seems like another vestigial thing from canonical flux that isn't really necessary.

Have you had a chance to read [this](http://rackt.github.io/redux/docs/recipes/ReducingBoilerplate.html#actions)?
Redux doesn't have a concept of “string constants”. Whether they are constants, or generated strings, or anything else is up to you. The only thing Redux cares about is **actions being serializable**.

Describing Redux as having “action type string constants” is as meaningless as describing a physics calculation function as using “integer constants”. Constants is what **you** write in your code—or generate if you like. By the point they get to Redux, they're just strings. How you get those strings is entirely your concern.

**Comment by gaearon** [comment]
>we instead allow the action tree to mirror the shape of the state tree:

If actions could always mirror the state tree, there would be no use in Redux (or Flux) because you'd just update the immutable tree directly. In real, large apps, the shape of the state tree rarely corresponds intuitively to the way you think about it. For example, you might want to express “follow user” action, but in reality, it corresponds to updates to `state.followersByUserId[followedUserId]`, `state.followedByUserId[currentUserId]`, `state.users[followedUserId]`, and `state.users[currentUserId]`. As the app grows, the same “simple” action may correspond to entirely unrelated state updates. **That's** the problem Redux and Flux are solving, letting you separate the descriptions of these updates (reducers), while keeping a single way to cause them (action).

**Comment by gaearon** [comment]
(I'm closing since this got some feedback & is easily findable in issues.)

**Comment by gaearon** [comment]
>However, we did get rid of dispatching by strings and replaced them with simple function calls.

This is exactly what this doc section talks about: http://rackt.github.io/redux/docs/recipes/ReducingBoilerplate.html#actions

>Actions are plain objects describing what happened in the app, and serve as the sole way to describe an intention to mutate the data. It’s important that actions being objects you have to dispatch is not boilerplate, but one of the fundamental design choices of Redux.

>**There are frameworks claiming to be similar to Flux, but without a concept of action objects. In terms of being predictable, this is a step backwards from Flux or Redux. If there are no serializable plain object actions, it is impossible to record and replay user sessions, or to implement hot reloading with time travel. If you’d rather modify data directly, you don’t need Redux.**

>It is a common convention that actions have a constant type that helps reducers (or Stores in Flux) identify them. We recommend that you use strings and not Symbols for action types, because strings are serializable, and by using Symbols you make recording and replaying harder than it needs to be.

>In Flux, it is traditionally thought that you would define every action type as a string constant.

>**Why is this beneficial? It is often claimed that constants are unnecessary, and for small projects, this might be correct. For larger projects, there are some benefits to defining action types as constants:**

>* It helps keep the naming consistent because all action types are gathered in a single place.
>* Sometimes you want to see all existing actions before working on a new feature. It may be that the action you need was already added by somebody on the team, but you didn’t know.
>* The list of action types that were added, removed, and changed in a Pull Request helps everyone on the team keep track of scope and implementation of new features.
>* If you make a typo when importing an action constant, you will get undefined. This is much easier to notice than a typo when you wonder why nothing happens when the action is dispatched.

>It is up to you to choose the conventions for your project. You may start by using inline strings, and later transition to constants, and maybe later group them into a single file. Redux does not have any opinion here, so use your best judgment.

**Comment by joebadmo** [comment]
Thanks for engaging with what may be some dumb or incompatible ideas. I appreciate it!

However, it seems I've misrepresented some ideas. I have read through the docs, which I'd like to applaud your documentation, it's truly top-notch, and one of the reasons we're probably going to switch.

There's very little about the guiding principles behind redux that I disagree with. Most of my concerns are ergonomic in nature, I think.

> Redux doesn't have a concept of “string constants”. Whether they are constants, or generated strings, or anything else is up to you. The only thing Redux cares about is actions being serializable.

I definitely agree with the idea of serializable actions and the benefits you get from them, but I'm not sure the "action object" as such is the only or best way to achieve those. In my proposed change, you could easily generate a serializable object from the context and name of the action, to generate the equivalent "history" of state mutations. (Currently we let baobab handle mutation history for us.)

> If actions could always mirror the state tree, there would be no use in Redux (or Flux) because you'd just update the immutable tree directly.

imho, it is still useful to isolate all possible state mutations and colocate them with the store definition, rather than interleave state mutation logic with e.g. the view layer.

I think your point also gets at another perhaps fundamental difference in how we're managing state in our implementation. Specifically:

> We suggest that you keep your state as normalized as possible, without any nesting.

Instead, we model our state nested in a way that makes sense for the application. That being the case, generally when it's appropriate for an action to mutate multiple nodes in the store, there's a common parent node in the state tree where the action can live:

```
let state = {
  foo: {
    bar: [],
    baz: [],
  }
};

let actions = {
  foo: {
    resetAll() {
      return { bar: [], baz: [] };
    },
    bar: {
      reset() {
        return [];
      }
    }
  }
};
```

We also avoid a lot of complexity in our actual action definition logic with the concept of "view state". I.e., we have "canonical state" in our store, which is mostly view-agnostic, and a pure `computeViewState` function which takes the canonical state and computes a state that's more easily consumable by the view.

So, if I understand your example correctly, the "follow user" action would only have to modify `state.users[currentUserId]`. The rest would be computed in the `computeViewState` function.

What this has meant for us so far is that state mutations are generally isolated to a fairly granular namespace, and we avoid a lot of potential for inconsistent data (how do you enforce that all of the interrelated state fields are updated in concert?).

In any case, thanks for bearing with me. If I'm totally barking up the tree, please let me know and I'll drop this.

**Comment by gaearon** [comment]
>In my proposed change, you could easily generate a serializable object from the context and name of the action, to generate the equivalent "history" of state mutations. (Currently we let baobab handle mutation history for us.)

I don't argue with this. I was responding to “we did get rid of dispatching by strings”. Whichever way you get those strings (constants, generating function names, etc) is your business. The only thing Redux cares about is they're **strings at the end** by the time you dispatch an action. Whether you use constants or generate strings from function name is not really relevant for Redux—it doesn't care. :-) This is the part of Redux that is completely up to you and does not warrant any changes to Redux itself.

>We also avoid a lot of complexity in our actual action definition logic with the concept of "view state". I.e., we have "canonical state" in our store, which is mostly view-agnostic, and a pure computeViewState function which takes the canonical state and computes a state that's more easily consumable by the view.

This is precisely what I'm advocating. Keep your state normalized, and have functions that compute "view state" when you need it to be tree-shaped. You can memoize them as described in [Computing Derived Data](http://rackt.github.io/redux/docs/recipes/ComputingDerivedData.html).

**Comment by gaearon** [comment]
Please forgive me for my withdrawing from this discussion because it comes up every now and then, and always goes nowhere. I created `redux/examples/real-world` example to show the power of reducer composition pattern. (See how it handles pagination.) If you know a better way to structure such mutations, please show by example :-). A trivial example doesn't help because it skips all the important details. Ideally I'd like to see each proposal to enhance Redux as a pull request to `real-world` example, showing how _that_ example will be simplified as a result.

**Comment by joebadmo** [comment]
No need to apologize, I appreciate the responses! I'll take a look at the `real-world` example. Thanks!

**Comment by brunolm** [comment]
I created a different approach https://github.com/brunolm/ts-react-redux-startup/commit/aa9d555026ae6e032423b916fb0a27ad6384b238

Basically it works the same way, but constant values are created automatically and there is no need to prefix constants. (Also if you are using TypeScript the object reference is still there, so it is really easy to rename it if you want to)

**Comment by mravko** [comment]
> > I really like redux, it seems like a distillation of all the good parts of "canonical" flux, but dispatching actions by strings seems like another vestigial thing from canonical flux that isn't really necessary.
> 
> Have you had a chance to read [this](http://rackt.github.io/redux/docs/recipes/ReducingBoilerplate.html#actions)?
> Redux doesn't have a concept of “string constants”. Whether they are constants, or generated strings, or anything else is up to you. The only thing Redux cares about is **actions being serializable**.
> 
> Describing Redux as having “action type string constants” is as meaningless as describing a physics calculation function as using “integer constants”. Constants is what **you** write in your code—or generate if you like. By the point they get to Redux, they're just strings. How you get those strings is entirely your concern.

Missleading starts [here ](https://redux.js.org/basics/actions#actions) when people don't understand why there is the "typically" word, meaning not always, meaning if they are not always constants they can sometimes be variables.

`const action= suffix=> ({
  type: "CHANGE_VALUE:" + suffix
});`

**Comment by jchnxu** [comment]
I love redux and the philosophy. But I got to admit 95% percent of my actions are SET_LOADING, SET_XXX. Which makes this annoying enough.

**Comment by markerikson** [comment]
@jchnxu uh... is there a reason why you bumped a thread from 6+ years ago? :)

This is _specifically_ why we created RTK's `createSlice` API. No more hand-writing action creators.

(and tbh we _don't_ see value in having magic autocompletion when you type `dispatch({type: |` and hit `CTRL-SPACE` - we expect users to import the right action creator from a given slice file and do `dispatch(todoAdded("buy milk"))`, etc.)

But yeah, this is also why we recommend _against_ having dozens of "setter" actions as well:

- https://redux.js.org/style-guide/#model-actions-as-events-not-setters

specifically _because_ it leads to such a proliferation of action types and extra mental overhead.

It's your code, and ultimately you can write it however you want, but there's good reasons why we've created RTK and recommend these patterns - we find that it leads to less code overall, and code that's more understandable.

**Comment by jchnxu** [comment]
Thanks for the reply! I didn't expect to get an answer lol.

1. The point is, writing applications are from a simple piece of data to complex ones. You cannot make good action abstractions from the start. You have to wait for the good abstraction to emerge and evolve your code. So there's a lot of boilerplate.

2. Thank you for your suggestion.
> (I'll also point out that action names like `SET_LOADING` suggest you probably aren't making use of RTK's `createAsyncThunk` or RTK Query APIs for managing data fetching, which would also eliminate the need to define those action types.)

How can I show a loader without the state.isLoading in a pull-to-refresh paginated list where I cannot use empty value/array as the loading state? You have to put the loading state somewhere to show the spinner right?

**Comment by markerikson** [comment]
@jchnxu : just to check, how much of Redux Toolkit have you actually looked at?

Yes, in order to show a spinner you'd normally need to dispatch an action and update loading state.  But, that's the point I was making above.  RTK's `createAsyncThunk` automatically creates and dispatches those `pending` actions for you, and RTK Query automatically gives you loading status flags if you use it.  I'm also confused why you're not using RTK's `createSlice` here.

I'd suggest reading these pages in the "Essentials" tutorial:

- https://redux.js.org/tutorials/essentials/part-2-app-structure#creating-slice-reducers-and-actions
- https://redux.js.org/tutorials/essentials/part-5-async-logic
- https://redux.js.org/tutorials/essentials/part-7-rtk-query-basics

I'll agree that code and abstractions and our understanding of the domain evolve over time, but there's also some mental approaches you can take that do lead to better code and less boilerplate.  The "events, not setters" philosophy is a big part of that.  (Doesn't mean you'll _never_ have a single `setX`-type action in the codebase, but even just writing the same code and naming it as `thingHappened` starts to change how you think about the behavior and the code.)

From my perspective, it feels like you're _trying_ to write code the hard way, and then feeling frustrated because you are in fact doing things the hard way :)
