### ISSUE TITLE
Fix vulnerability in Server Rendering recipe

### ISSUE THREAD

**Issue by gaearon** [rackt/redux#635]
https://twitter.com/ericf/status/636752569025622017

@timdorr 
@hedgerh

**Comment by timdorr** [comment]
Looks like the aforementioned library has some security issues too: yahoo/serialize-javascript#5

Does anyone know any other possible sanitization methods/libraries we could use in this case? There's gotta be something in npm...

**Comment by ericf** [comment]
@timdorr You should look at the full issue, it might cause an error on the server, but unlikely to result in an XSS to the browser. Most Yahoo sites have been using this code for years.

**Comment by timdorr** [comment]
Yeah, I'm trying to grok where the security issue lives. We're serializing an internal state variable, not raw input from the user. The only input is the counter variable, which I `parseInt` on anyways. 

I'm probably missing something. What should I be looking for?

**Comment by ericf** [comment]
The example is fine how it is today, the problem is that people will use this pattern in their apps that do have UGC and open an XSS attack vector. Since the examples serve as docs, my suggestion on Twitter was to use something that will help people holster this footgun.

**Comment by timdorr** [comment]
That's certainly true, but the use of `JSON.stringify` here isn't on anything user generated that hasn't already been sanitized. Suggesting we use a generalized function to sanitize input, rather than looking at the input directly, is dangerously hand wave-y. 

I can certainly add some text to the docs warning of the potential pitfalls of accepting user input. In particular, emphasizing the importance of the `parseInt` call and other sanitization methods on input. 

Another good idea would be to not just pass in initial state, but instead dispatch some actions to an empty store to populate it. Then you could make sure your reducers are hardened, which applies to both the server and the client.

**Comment by ericf** [comment]
Defense in depths. Surely sanitize input values, but the context here is outputting inside a `<script>` and that requires special sanitation and escaping so browsers don't prematurely interpret a closing `</script>` — do both.

Outputting inside a `<script>` is the _exact_ use case for why this package was written and has helped to patch XSS vectors exploited in production.

**Comment by timdorr** [comment]
That is true. I probably wasn't getting the `<script>` output in JSON taking priority over the JS itself. 

I think a security section towards the end is warranted. Especially since universal rendering opens up the attack surface area. I'll see about adding that in tonight.

**Comment by vjeux** [comment]
Please note that the issues I found are very very unlikely to be exploitable. Just some edge cases that could be better handled

**Comment by timdorr** [comment]
Just added #641 to (hopefully) address this.
