### ISSUE TITLE
I built a way to make redux more modular. I thought you might like it.

### ISSUE THREAD

**Issue by ariporad** [rackt/redux#647]
Hi,

I'm not sure if this is the right place to post this, but I saw the [ecosystem] tag, so I thought I'd post.

I've spent the past two days working on [modular-redux](/ariporad/modular-redux), a library who's purpose it to help you take the global out of global reducer. It also manages action types, eliminating the need for a global reducer or global file of action type constants.

I really hope you take a look at it, I think it's pretty cool.

Thanks, Ari

*EDIT:* I should have said that I think redux is a really awesome tool, and by far my favorite version of flux.

**Comment by gaearon** [comment]
Does it work with hot reloading?
Does it work with time travel?
Does it work with [hot reloading combined with time travel](https://github.com/gaearon/redux-devtools)?

These were explicit design goals of Redux.

**Comment by ariporad** [comment]
I haven't tested it, althought I'm not sure why it wouldn't.

Let me get back to test it and get back to you. Is there a test repo of some kind I can use to easily test it?

**Comment by ariporad** [comment]
I should say that I don't see any reason that it wouldn't because internally, it just calls store.replaceReducer with the result of combineReducers. Also, adding a reducer to a piece of state which already has one just overrides it, so I doesn't seem like it should be a problem. But let me test it though.

**Comment by gaearon** [comment]
>Let me get back to test it and get back to you. Is there a test repo of some kind I can use to easily test it?

You can start with `redux/examples/counter`, it's the simplest one. Note you can hot reload both component and reducer logic. Time travel is trickier: you'll need to port parts of Redux DevTools too to see if it works. 

>Also, Redux has a global reducer, and virtually requires a global list of action types. Weren't we always told not to use globals?

It's like saying React components are global because you have a "global root component". Reducers are composed, just like components are composed. They are not global in any way.

**Comment by gaearon** [comment]
>The ultimate goal of this project (and my other ones too), is to allow you to write (at least part of your codebase) so that if you just remove the single javascript file, the test (which is next to it), and the import statement, there will be no trace that the file ever existed. No far-flung css, no code in the reducer or action type files, nothing.

Don't Reducer + Action Creator bundles cover what you aimed to solve?
https://github.com/erikras/react-redux-universal-hot-example/blob/master/docs/Ducks.md

You don't have to put your reducers into `reducers.js`. It's up to you to structure your code, and to find good patterns to do so, that make sense for your apps.

**Comment by gaearon** [comment]
Looking at the [source code](https://github.com/ariporad/modular-redux/blob/master/src/index.js), what you claim to be modularity is actually making `store` a singleton, and exposing a few methods to attach stuff like action creators to it.

This is in approach we considered early for Redux, but it makes [server rendering](rackt.github.io/redux/docs/recipes/ServerRendering.html) very difficult. On the server, you'll want to have a single Redux store instance **per request**. We didn't want people to get stuck like people used to get stuck with traditional Flux, so that's the reason store isn't a singleton in Redux, and doesn't have methods like `addActionCreator` which are executed at the module level.

**Comment by ariporad** [comment]
Hmm... I never knew about ducks. That basically solved my problem! Thanks!

(This was a waste of time, but I had fun, so whatever).

**Comment by gaearon** [comment]
That said not everybody want to render apps on server, and in this case, such approach may be a convenience. I still prefer explicit import for the reducers though, but it's really up to you. :-)

We don't want to lock people out of server rendering, but if that simplifies your life, of course you can use this pattern.
