### ISSUE TITLE
setInputValue(val) question

### ISSUE THREAD

**Issue by tkiethanom** [rackt/redux#662]
In the real world example Explore.js line 22. It mentions this function isn't the correct way to do this. What is the correct way to do this? What does it mean to make it controlled and maintaining a state for it?

**Comment by timdorr** [comment]
It means to bind the value of the input to state. That is, rather than dealing with the DOM directly, we would set `<input value={this.props.value}>`. It's described in [the React docs](https://facebook.github.io/react/docs/forms.html#controlled-components). 

Binding it back to some value in the store is fairly involved compared to just simply setting the DOM node's value. But if you were building a real app, you might go to that trouble for an important form component.
