### ISSUE TITLE
Create Typescript definition file

### ISSUE THREAD

**Issue by pdeva** [rackt/redux#696]
It would be really nice to have a Typescript definition file for redux at DefinitelyTyped

**Comment by s-panferov** [comment]
@pdeva they already has one https://github.com/borisyankov/DefinitelyTyped/blob/master/redux/redux.d.ts

I have a plan to use redux with TypeScript, so I'm making more complete `.d.ts` file right now.

**Comment by timdorr** [comment]
@pdeva Is that file sufficient? I'm not a TS user yet.

**Comment by gaearon** [comment]
Closing as duplicate of #206.

**Comment by pdeva** [comment]
the current typescript definition does not contain a declaration for the `compose` method which seems to be imported and used in the redux-devtools example code her:
https://github.com/gaearon/redux-devtools

**Comment by gaearon** [comment]
Indeed, it's missing. For 1.0, I don't think it's worth adding (signature changed since), but for 2.x, `compose` should match [`_.compose` from Lodash](https://github.com/borisyankov/DefinitelyTyped/blob/7a3ca1f0b8a0960af9fc1838f3234cc9d6ce0645/lodash/lodash.d.ts#L5540).. I think. Feel free to make a PR to DefinitelyTyped.

**Comment by pdeva** [comment]
I just created the pull request for this:
https://github.com/borisyankov/DefinitelyTyped/pull/5796

**Comment by gaearon** [comment]
Please help review the new official typings in https://github.com/reactjs/redux/pull/1413.
