### ISSUE TITLE
Documentation/Async Actions: Better differentiation between Action Creators and Actions

### ISSUE THREAD

**Issue by matthewmueller** [rackt/redux#726]
Just dropping in here to mention that I found the documentation confusing on what an action **actually** is. The "Async Actions" section seems to suggest that actions can be async, which makes me think that they are functions. The "Actions" section suggests that actions are payloads of information, which suggests they are objects. 

Based on the glossary, I think "Async Actions" should actually be "Async Action Creators". Not as elegant, but I think it's slightly less confusing. 

Otherwise, great work on the comprehensive documentation!

**Comment by edge** [comment]
The difference is unclear because async actions need the thunk middleware or something similar to use. In that case, *anything* that can be dispatched could in fact be considered an action (e.g. Promise, thunk, etc.), when really, only plain objects with a `type` property are actions.

When you start dispatching functions that return functions (depending on your use case), it becomes difficult to give everything a unique name.

It's probably a good idea to move away from "async actions," but "async action creators" might not be the best way to go.

**Comment by matthewmueller** [comment]
> The difference is unclear because async actions need the thunk middleware or something similar to use. In that case, anything that can be dispatched could in fact be considered an action (e.g. Promise, thunk, etc.), when really, only plain objects with a type property are actions.

Yah, I guess I would probably not say that an action is anything that goes into the dispatch function, I would say it's what actually goes into the store.

**Comment by gaearon** [comment]
Async action is

>anything that goes into the dispatch function

Action is

>what actually goes into the store

Async actions can be anything, as long as middleware turns them into proper actions by the time middleware chain ends.

If you see a way of improving the doc, please send a PR!
