### ISSUE TITLE
save Store as global variable ?

### ISSUE THREAD

**Issue by bultas** [rackt/redux#776]
We have some cases where would be handy, if we can import module/variable where will be stored Store with dispatch function and app state. 

for example:

We create Store in app root and save it via function in another module.

```
-------- globalStore.js ------------

let Store = null;

export function saveStore(createdStore) {
    Store = createdStore;
}
export function getStore() {
    return Store;
}
```
and now if we need read some state from our App State or use Dispatch function we don't have to pass it from root or use Connect function (which is focused on React components) instead of we can import that globalStore.js module and get the whole Store and use it in any our modules (request helpers for example)

I would like to ask you, if this is good or bad practice.

Thank you

**Comment by gaearon** [comment]
This is an OK practice, but note that, if you ever want to add server-side rendering with Node, you're making it harder. With server side rendering, you'll want to have a separate store per request—not one a singleton. Similarly, you're making it harder to test the app.

Most of the cases, when you want to have a singleton store, what you *really* want is to use async action creators with something like [redux-thunk](https://github.com/gaearon/redux-thunk). It lets you write methods that depend on `dispatch` and `getState` but without actually importing a Store—so that you can write custom logic depending on it, and `dispatch()` this action creator from inside the component.

**Comment by bultas** [comment]
Thank you for explanation.
We already use these async action creators. But in several of our cases it seemed passing `dispatch` or `getState` from action creator down to our helpers as unnecessary cluttering the code..

**Comment by gaearon** [comment]
Why would you want to pass `dispatch` or `getState` to helpers? Maybe if you could provide some code that would help.

**Comment by mattdell** [comment]
Here is an example I'm struggling with in Redux, @gaearon.

```
import superagent from 'superagent';
import ApiActions from '../../actions/ApiActions';

export default class ApiUtils {
	static makeAjaxRequest(data) {

		let request = superagent(data.method, data.url)
			.set('Accept', 'application/json')
			.set('Content-Type', 'application/json');

		if (data.requestData) {
			request.send(data.requestData);
		}

		request.end(function(err, res) {
			if (err) {
				// Need to access store here!
				store.dispatch(ApiActions.handleError(err, res));
				return;
			}

			// And here!
			store.dispatch(ApiActions.handleSuccess(res));
		});
	}
}

```

The thinking being if I want to handle the response or error with an action that will then determine what to update in the store. I can then handle a transition using this.props.history once my root component sees an update in the store.

I would certainly appreciate your thoughts on this approach.

**Comment by johanneslumpe** [comment]
@mattdell It might be easier to not inject the store into your api, but to have an api middleware which will inject your api into your actions. This als enables you to transition based on an action (shameless plug: take a look at https://github.com/johanneslumpe/redux-history-transitions for the latter).

For a generic api middleware, this might help: https://github.com/erikras/react-redux-universal-hot-example/blob/master/src/redux/middleware/clientMiddleware.js

**Comment by BorelTung** [comment]
Here is a good practice of managing a component globally, [Redux Toastr](https://github.com/diegoddox/redux-toastr).
It uses [EventEmitter3](https://github.com/primus/eventemitter3) to dispatch actions.

**Comment by donpark** [comment]
A reasonable alternative solution is to use a module level function that uses an opaque object representing context to retrieve context-specific store instance which would be  used like this:

    // client-side
    var store = require('redux').getStore(window)

    // server-side
    function handleFoobar(req, res) {
      var store = require('redux').getStore(req);
    }

**Comment by gaearon** [comment]
We don’t want to provide something like this. Holding onto the store user creates is user’s responsibility. Redux is not different from any other library in this regard.

When you need the store, pass it to the parts of your code that need it. Since you create the store, it is your responsibility to ensure it is passed wherever it is necessary. For example, to solve https://github.com/rackt/redux/issues/776#issuecomment-158648858 you would need to pass `store` (or `dispatch` function) to `makeAjaxRequest`.

Alternatively one could use middleware like Redux Thunk to inject `dispatch`. I explained the difference between two approaches [here](http://stackoverflow.com/a/34599594/458193). If you need to pass something, you need to pass something. Don’t look for the library to solve this for you. It’s just a matter of passing data or using some dependency injection mechanism that is out of the scope of this library.

**Comment by donpark** [comment]
Understood. I wasn't suggesting changes to Redux which is more of a toolbox of a core module with related modules for integration and use-case specific extension, a toolkit if you will.

However, I think Redux needs a framework on top to make it easier and simpler to use for most common use-cases because I found it surprisingly tedious to use in practice. Async operations for example involves several actions and reducers instead of a single callback. While requests and responses can be seen as actions, they're more phases of an action than individual actions.

**Comment by gaearon** [comment]
>However, I think Redux needs a framework on top to make it easier and simpler to use for most common use-cases

You are welcome to create one :wink: .

Redux is not an app-building framework. It’s a basic building block for predictable state updates. You can (and probably should) build on top of it, and share valuable abstractions you discover on the way there.

For example, https://github.com/shastajs attempts to do something like this, and I’m sure we’ll see more in the future.

>Async operations for example involves several actions and reducers instead of a single callback

Do they, really? I think you are conflating “Redux best practices” with what Redux actually is.

It is completely up to you how to choose when to divide actions. Nobody is preventing you from using the same action type for requests and responses. Nobody is forcing you to write action creators when you can dispatch inline AJAX calls from components:

```js
// reducer
const users = (state = { done: false }, action) => {
  if (action.type === 'FETCH_USERS') {
    return { ...state, done: action.done, users: action.users }
  }
  return state
}

// component
handleClick() {
  let { dispatch } = this.props
  dispatch({ type: 'FETCH_USERS', done: false })
  fetch('/users').then(res => res.json()).then(users =>
    dispatch({ type: 'FETCH_USERS', done: true, users })
  )
}
```

How is this much different from a callback? Not much :-). Except for using an action instead of directly causing the update. If you want to give up that part too, you just don’t need Redux.

It is up to you to choose whether you like Redux dense or sparse. We prefer sparse code in examples but you are free to not write “the boilerplate”.

**Comment by donpark** [comment]
> How is this much different from a callback? Not much :-).

Well, I think we got as much as we can out of this.
Thx for the detailed responses. I do appreciate that at least. :-)

**Comment by stevemao** [comment]
NOTE: I feel confused with the term *singleton store*.
"*singleton store* is not recommended" doesn't mean we can create more than one store in the app. It just means the store should be passed through `<Provider>` instead of exporting and importing it from a module.

**Comment by majo44** [comment]
This is old thread, but what do you think about such smart/hacks solution which is using zone.js
```
// store..js
// universal store factory
export createStore() { ....}

// client.js
// on client side
import {createStore} from './store';
window.store = createStore();

// server.js
// on server side
import {createStore} from './store';

app.use((req, res, next) => {
    // so on each request, we can put new store to the local thread storage (by zone.js)
   // and run next in that zone
    Zone.current.fork({
      name:'store'
      properties: {
          store: createStore();
      }
  }).run(next);
});

// now we are creating global getter for store which will take the store from thread storage, 
// instead of regular 'global' object
Object.defineProperty(global, 'store', {
   get: () => {
      return Zone.current.get('store');
   }
}

// and we can use the store in next middlewares
app.use((req, res, next) => {
    console.log(store.getState());
});

```
