### ISSUE TITLE
Hot Reload Actions

### ISSUE THREAD

**Issue by ronag** [rackt/redux#782]
Anyone done any work or have any ideas on hot reloadable actions?

https://github.com/este/este/issues/482

**Comment by gaearon** [comment]
They should work out of the box.

**Comment by gaearon** [comment]
(With Webpack Hot Module Replacement, updates to stateless modules "bubble up" until some module handles them. In case of action creators, updates will bubble to components, which are handled by `react-transform-hmr`.)

**Comment by steida** [comment]
@gaearon Can you point us to any starter kit, where actions are hot reloadable? I tried some without success.

**Comment by gaearon** [comment]
Examples folder in this project should work.

**Comment by gaearon** [comment]
Oh, I see now. This got broken after the switch from React Hot Loader to React Transform (#690). The reason for this is that `babel-plugin-react-transform` has no idea `examples/counter/containers/App.js` is a component, and doesn't enable hot reloading for it.

Since this is an issue unrelated to Redux, please track it in https://github.com/gaearon/babel-plugin-react-transform/issues/26. You can also keep using React Hot Loader until it is fixed. With React Hot Loader, action creators should get reloaded just fine.

**Comment by gaearon** [comment]
You might be interested in https://github.com/reactjs/redux/pull/1455.

**Comment by gaearon** [comment]
This is fixed in [React Hot Loader 3](https://github.com/gaearon/react-hot-boilerplate/pull/61).
It is built with lessons learned from both React Hot Loader and React Transform.
It’s still in alpha but I encourage you to [check it out](https://github.com/gaearon/react-hot-boilerplate/pull/61)!

**Comment by steida** [comment]
Awesome work Dan, you are the man :-)
