### ISSUE TITLE
Dispatching actions

### ISSUE THREAD

**Issue by tim-cools** [rackt/redux#806]
Hi,

I'm quit new to the flux/redux so I might be missing something obvious :)

I was wondering why it is necessary to have the dispatch method injected in the props of components and then invoke it from the component each time an action is dispatched. Doesn't it makes more sense to hide this away from components and to encapsulate this inside the actions module? Something like this:

store.js
--------
```
let store = ...

export dispatch = store.dispatch;
```
actions.js
----------
```
import state from './state'

function logonPending() {
  return { ... }
}

export actions = {
  logonPending = () => store.dispatch(logonPending())
}
```

component.js
------------
```
import actions from '../actions'

...

actions.logonPending();

//instead of 

this.props.dispatch(actions.logonPending());

...
```

Because we have a lot more components in comparison to action definitions it makes more sense for me to do the delegation of the dispatch once in the action module. Instead of in each component separately. This reduces coupling: only one module is doing the dispatch. Because the action module calls the state module it is also usable server side if the state module returns the current store I guess. 

This also makes the components easier to test. I just need to verify whether the function of the actions module is called from a module. Otherwise I have to verify the data that is used to call the dispatch of the props method is correct. And components don't care about the data structure of the action anyway. They just want to notify the store that something has changed.

You can still export the action creators if you want to test them, but I believe the components are more important to test.

Any feedback welcome!

**Comment by johanneslumpe** [comment]
You might want to check out https://github.com/rackt/redux/blob/master/src/utils/bindActionCreators.js - it allows you to automatically bind your action creators to the dispatch method. The result of this then gets injected into your component as props, so you will end up being able to do `this.props.someAction()` instead of wrapping it with `this.props.dispatch()`.

Also note that what you are proposing (exporting the dispatch function from a module) will not work when creating a universal application, because you have to re-create the store on each request but you cannot re-create a module. So all your action creators would only have a reference to the first instance.

Also check out https://github.com/rackt/react-redux/ - especially the [`connect` functionality, as it allows you to map the `dispatch` function to props](https://github.com/rackt/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options).

**Comment by gaearon** [comment]
>Also note that what you are proposing (exporting the dispatch function from a module) will not work when creating a universal application, because you have to re-create the store on each request but you cannot re-create a module. So all your action creators would only have a reference to the first instance.

That's the main reason why `dispatch` is being injected. You want different stores for every server request.

**Comment by tim-cools** [comment]
thanks for the link and feedback! that look already cleaner, but then I still have more code and is more difficult to test than simply calling a method on an imported `actions` object.

> Also note that what you are proposing (exporting the dispatch function from a module) will not work > when creating a universal application, because you have to re-create the store on each request but > you cannot re-create a module. So all your action creators would only have a reference to the first 
> instance.

I agree that you can not regenerate a module. But it is perfectly possible to export a dispatch delegate from state.js that calls the current state instead of a global state.

```
var state = createStore(reducers)

export function setState (newState) = state = newState; // or create a new for each request

export function dispatch (action) => state.dispatch(action);
```

Where state is the global state client-side state or the current state when rendering on the server.

**Comment by johanneslumpe** [comment]
@tim-cools No, this will not work. Because multiple requests will start to clobber your "singleton". If two requests come in at almost the same time - the 2nd one will overwrite your store. And if you have multiple dispatches - possibly additional ones after a first async one - those additional dispatches from the 1st request will now happen on the store from the 2nd request.

What you are attempting to do here is error-prone and brittle ;)

**Comment by tim-cools** [comment]
@johanneslumpe you are right! bad and dangerous example :-)

we could however store the state in a context object only valid for a request

https://github.com/michaelkrone/request-context

any issues with that?

**Comment by johanneslumpe** [comment]
My issue with that: it does not work on the client, now your code is less universal.You will need a condition within your module to check whether you are on the server and if so, require the module and use the value from the context to dispatch. It might work and if that's your cup of tea feel free to try it :)

**Comment by gaearon** [comment]
@tim-cools 

Anyway.. Nobody prevents you from writing code this way. :-) If you're confident you won't be doing server rendering (or if you're comfortable with putting it somewhere else than [React context](https://medium.com/@skwee357/the-land-of-undocumented-react-js-the-context-99b3f931ff73) which is how `<Provider>` works) feel free to write code as you suggest. However this will not be the default way we recommend in the examples and docs.

**Comment by tim-cools** [comment]
I was working on a web-socket client and had not dispatch function or react/redux context to invoke actions from when I get data from the server. So I definitely need some way to invoke actions without his. I will give it a try without the dispatch also from the components, I prefer the clutter in my infrastructure code instead of in my components.  

My back-end API is .NET anyway, and I'm not sure yet how I will handle server side rendering.

Thanks for the feedback guys! Great support for a Saturday ;-)

**Comment by gaearon** [comment]
@tim-cools `dispatch()` is a method on the store object you get with `createStore()`. React Redux passes it for convenience, but really, since you're creating the store, you're free to pass it anywhere you like and then call `store.dispatch()`.
