### ISSUE TITLE
Sanity checks in production builds

### ISSUE THREAD

**Issue by jarsbe** [rackt/redux#816]
I was nosing around and I noticed that the sanity checks in `combineReducers` are invoking each reducer - not once, but twice upon boot! I figured this seems like an unnecessarily bottleneck during boot. It make sense in a development environment but is it really necessary in production? 

I was wondering if a "santity checkless" build is a common thing for libraries?

**Comment by gaearon** [comment]
It is not going to affect the boot time in any meaningful way. The reason we're keeping them in production is to avoid the situation where you have different stack traces in dev and prod. If those sanity checks fail, it means there *is* a mistake in your code, and it *will* blow up later. But you'll get a totally different stack trace in production, which will be mysterious because you won't be able to reproduce it in development.

For example, React also does certain assertions both in development and production because otherwise it would be very hard to trace something-has-gone-really-bad scenarios.

We don't plan to remove these checks. However, if you feel strongly about it, you can write a `combineReducers`-ly code by hand:

```js
function app(state = {}, action) {
  return {
    something: something(state.something, action),
    somethingElse: somethingElse(state.somethingElse, action)
  };
}
```

and have full control over it.

**Comment by jarsbe** [comment]
@gaearon I thought you were on holiday with your pink crocs!? Cheers for the explanation though :crocodile:
