### ISSUE TITLE
Can you provide examples for the ASP.NET TypeScript ecosystem?

### ISSUE THREAD

**Issue by cveld** [rackt/redux#889]
As a Microsoft consultant I am eager to see ready-to-use examples that are based on the ASP.NET 4.6 or even 5 stack ideally combined with TypeScript. Any plans?

**Comment by tracker1** [comment]
You could add a type definition... http://definitelytyped.org/

Though, to be honest, this has almost nothing to do with ASP.Net, and most of the exposed interfaces are meant to accept functions.

**Comment by gaearon** [comment]
We're only going to support a single server rendering example—with Node, because that's what most people who do server rendering use, and it's easiest to maintain because it uses the same ecosystem and tooling (Babel, NPM, etc).

We have a [recipe on server rendering](http://rackt.github.io/redux/docs/recipes/ServerRendering.html) which may give you an idea of how to make it work on other platforms as long as they can run some JavaScript. If you're not interested in server rendering, from ASP .NET's point of view, using Redux isn't any different from using Backbone or any other client-side library.

I'm closing since there is nothing actionable here for us, but feel free to continue the discussion.
