### ISSUE TITLE
Example Computing Derived Data for reducers

### ISSUE THREAD

**Issue by peteruithoven** [rackt/redux#956]
I'm curious why nobody explicitly seems to use reselect inside reducers. When (multiple) reducers use "expensive" derived data this seems like a obvious optimization possibility. 
Would it be an idea to add a basic example to the [Computing Derived Data](http://rackt.org/redux/docs/recipes/ComputingDerivedData.html) page? 
It not being mentioned in the reselect Readme or that Redux doc page might give the impression that it's not a good idea.

**Comment by nhagen** [comment]
I would think that having derived data in reducers at all should be discouraged because its just duplication of data. Can you provide a gist of using `reselect` in a reducer?

**Comment by peteruithoven** [comment]
I'll try to come up with a simple example. 
I think it's relevant when multiple reducers need to perform logic based on the same "expensive" derived data.

**Comment by peteruithoven** [comment]
So this would be a very contrived example: https://gist.github.com/peteruithoven/348c11afbd10cf81c01d

**Comment by peteruithoven** [comment]
The following quote actually seems to discourage my idea. 
> selectors are the step between your Redux store state and your components—they are not inside your reducers. 

From: http://stackoverflow.com/a/32922461/1544200

**Comment by gaearon** [comment]
I don't think your example really explains the issue.
It's very incomplete:

```js
  case COMPLETE_ALL_VISIBLE_TODOS: 
    const visibleTodos = visibleTodosSelector(state).visibleTodos;
    // mark all these todos as completed
    break;
```

How would they be marked? What state would you return?

I think you'll find that as your example gets closer to a real world example, you'll be doing unnecessary calculations. When you need memoization inside a reducer, it's a sign you might want to structure data in a different way, e.g. pull out boolean flags into arrays of IDs. You also need to consider carefully which actions happen often and which don't, and what exactly you're optimizing for.

I'll close but if you come up with a more nuanced example you believe to *need* memoization, I'll be happy to take a look.

**Comment by HeyImAlex** [comment]
I think your example doesn't give much benefit; `visibleTodosSelector` could just as well be a utility function, because the result of `COMPLETE_ALL_VISIBLE_TODOS` and `DELETE_ALL_VISIBLE_TODOS` should be new arrays, which means reselect is just recomputing for every action. In most cases you couldn't use that same selector in your view code, as your reducer probably only deals with a slice of the complete state, and selectors take the whole state as input. If this is your _only_ reducer and you use the `visibleTodosSelector` in your view, then you'd get the benefit.

Reselect is particularly bad for this because it needs the whole state, something that nested reducers don't have knowledge of. When you frame the question as "is memoization an optimization possibility when I need to compute a value more than once" the answer is yes.

However, it's an optimization.
