### ISSUE TITLE
How to handle mapStateToProps for getting entities from ids? 

### ISSUE THREAD

**Issue by vimalceg** [rackt/redux#991]
In Real world example, mapStateToProps(UserPage.js) always fails for shallowEqual. 
const starredRepos = starredPagination.ids.map(id => repos[id]) return new object always

I tried counter inside real-world example. when i increase counter, userpage gets rerender
https://github.com/vimalceg/redux/tree/master/examples/real-world

Can I handle using shouldComponentUpdate inside wrappedcomponent? 
or
Pass entity and ids as a props and process inside component?
or
Any best way to get list of id to entities

best practice for mapStateToProps? 

Thanks

**Comment by gaearon** [comment]
Use https://github.com/rackt/reselect to memoize derived data.

http://redux.js.org/docs/recipes/ComputingDerivedData.html

**Comment by sibeliusseraphini** [comment]
@vimalceg did u manage to find a solution for this?

**Comment by Aweary** [comment]
@sibeliusseraphini 
> Use https://github.com/rackt/reselect to memoize derived data.

**Comment by sibeliusseraphini** [comment]
@Aweary could you please provide an example using reselect of this line:

`const starredRepos = starredPagination.ids.map(id => repos[id])`

**Comment by Aweary** [comment]
It might look something like:

```js
import {createSelector} from 'reselect'

const staredRepoSelector = createSelector(
  starred => starred.id,
  ids => ids.map(id => repos[id])
);

const starredRepos = startedRepoSelector(starredPagination);
```

**Comment by sibeliusseraphini** [comment]
one problem of reselect is that the resultFunc will only accept the inputSelectors that you passed to the createSelector function, so you can't access `repos` variable inside of it, only if `repos` is an input selector as well.

However, I don't want to render my component when a new **repo** is added to **repos** to render, I want to render again only when **starred.ids** changes

@Aweary let me know if you need more information, thanks

**Comment by Aweary** [comment]
Where is `repos` coming from, `props`?

**Comment by sibeliusseraphini** [comment]
`repos` is comming from `state.entities.repos` (normalizr style)

here: https://github.com/reactjs/redux/blob/master/examples%2Freal-world%2Fcontainers%2FRepoPage.js#L79

**Comment by vimalceg** [comment]
> However, I don't want to render my component when a new repo is added to repos to render, I want to render again only when starred.ids changes

Just hook I don't know how to handle properly. hook works only shallow compare of createselector.
https://gist.github.com/vimalceg/315c81d827478135abb2c80f6e8b408a

**Comment by Aweary** [comment]
```js

**Comment by pierrepinard-2** [comment]
@sibeliusseraphini 

> However, I don't want to render my component when a new repo is added to repos to render, I want to render again only when starred.ids changes

For this kind of optimization, this should be done directly in the shouldComponentUpdate() method of the involved component. Please see [my answer](http://stackoverflow.com/a/36446713/3584383) to your question on StackOverflow.

**Comment by frankwallis** [comment]
const reposSelector = state => state.entities.repos;
const idSelector = (state, props) => props.id;

const mapStateToProps = createSelector(
   reposSelector,
.  idSelector,
.  (repos, id) => repos[id]
);

If you are using connect and repos[id] returns the same value then the component will not be rerendered, because connect implements shouldComponentUpdate to compare props with previous values.

Apologies for formatting, I'm on a bus.

**Comment by sibeliusseraphini** [comment]
@frankwallis this only works if I have only one ID, how about to this case:

`const starredRepos = starredPagination.ids.map(id => repos[id])`

Having a list of IDs instead

**Comment by frankwallis** [comment]
There are have a number of options - 

reselect lets you specify a different equality checking function [see here](https://github.com/reactjs/reselect#defaultmemoizefunc-equalitycheck--defaultequalitycheck), so you could replace it's shallow equality check with lodash ```isEqual```, which would return true if the two arrays contained the same ids.

Otherwise as @pierrepinard-2 says you can do a different equality check in the ```shouldComponent``` update method of your list component.

Lastly if you just want to suppress re-rendering of all the list items then you could make each of the list items into a ```PureComponent``` [see here](https://github.com/gaearon/react-pure-render). Then each of the list items will do a shallow comparison of their props and not re-render if they have not changed. This will result in the list's render method getting called, but the render method of the items will not get called if they have not changed, which will significantly improve performance.

**Comment by sibeliusseraphini** [comment]
thanks everybody for the help and for all the provided options/solutions.

I moved the connect to a bottom component, than I could solve the issue with map, I will try the other solution as well
